hmcts/vh-bookings-api

BookingsAPI/Bookings.API/Extensions/CloudRoleNameInitializer.cs, BookingsAPI/Bookings.API/Startup.cs
n/a
Added in cloud role name as in https://github.com/hmcts/vh-admin-web/pull/74.
```
[ ] Yes
[X] No
```
=> Added in role name initializer for app insights

BookingsAPI/Bookings.API/appsettings.json
=> changed queue name to booking

BookingsAPI/Bookings.API/Controllers/ParticipantsController.cs, BookingsAPI/Bookings.API/Controllers/PersonsController.cs, BookingsAPI/Bookings.Api.Contract/Responses/PersonSuitabilityAnswerResponse.cs, BookingsAPI/Bookings.DAL/Bookings.DAL.csproj, BookingsAPI/Bookings.DAL/Migrations/20190604142022_update_suitability_table.Designer.cs, BookingsAPI/Bookings.DAL/Migrations/20190604142022_update_suitability_table.cs, BookingsAPI/Bookings.Domain/Participants/Participant.cs, BookingsAPI/Bookings.Domain/SuitabilityAnswer.cs, BookingsAPI/Bookings.IntegrationTests/Features/Persons.feature, BookingsAPI/Bookings.IntegrationTests/Features/Persons.feature.cs, BookingsAPI/Bookings.IntegrationTests/Helper/TestDataManager.cs, BookingsAPI/Bookings.IntegrationTests/Steps/HearingsSteps.cs, BookingsAPI/Bookings.IntegrationTests/Steps/PersonsSteps.cs, BookingsAPI/Bookings.UnitTests/Controllers/PersonsControllerTest.cs
https://tools.hmcts.net/jira/browse/VIH-4247
- Fixed a bug that stopped from returning hearing data for a person if suitability answers didn't exist
- Integration tests
```
[ ] Yes
[ x] No
```
=> Fixed a bug that stopped from returning hearing data for a person if suitability answers didn't exist

BookingsAPI/Bookings.API/Controllers/ParticipantsController.cs, BookingsAPI/Bookings.DAL/Queries/GetParticipantsByUsernameQuery.cs
https://tools.hmcts.net/jira/browse/VIH-4718
Change the Get query to take List instead of IEnumberable
```
[ ] Yes
[ ] No
```
=> Vih 4718 get participants endpoint

BookingsAPI/Bookings.IntegrationTests/Helper/TestDataManager.cs
N/A
Clean up test data from integration tests
```
[ ] Yes
[x] No
```
=> clean up cases and persons for an integration test

BookingsAPI/Bookings.Domain/Participants/Individual.cs
https://tools.hmcts.net/jira/browse/VIH-4732
Participant Individual had not address previously, fix edit
```
[ ] Yes
[ X] No
```
=> Fix edit existing participant that had not address previously

BookingsAPI/Bookings.API/Controllers/HearingsController.cs, BookingsAPI/Bookings.AcceptanceTests/Features/Hearings.feature, BookingsAPI/Bookings.AcceptanceTests/Models/UpdateBookingStatusRequest.cs, BookingsAPI/Bookings.AcceptanceTests/Steps/HearingsSteps.cs, BookingsAPI/Bookings.Api.Contract/Requests/Enums/UpdateBookingStatus.cs, BookingsAPI/Bookings.IntegrationTests/Features/Hearings.feature, BookingsAPI/Bookings.IntegrationTests/Steps/HearingsSteps.cs, BookingsAPI/Bookings.UnitTests/Controllers/HearingsControllerTest.cs, BookingsAPI/Testing.Common/Builders/Domain/VideoHearingBuilder.cs
https://tools.hmcts.net/jira/browse/VIH-4121
Change status of hearing to created and raise event to notify video app that the hearing is confirmed
```
[ ] Yes
[ X] No
```
=> Notify video if hearing was confirmed-4121

BookingsAPI/Bookings.API/Controllers/PersonsController.cs, BookingsAPI/Bookings.AcceptanceTests/Steps/PersonsSteps.cs, BookingsAPI/Bookings.Api.Contract/Responses/PersonSuitabilityAnswerResponse.cs, BookingsAPI/Bookings.IntegrationTests/Steps/PersonsSteps.cs
https://tools.hmcts.net/jira/browse/VIH-4300
```
[ ] Yes
[ x] No
```
=> VIH-4300: Adding flag to suitability answers models

BookingsAPI/Bookings.Common/Bookings.Common.csproj, BookingsAPI/Bookings.Infrastructure.Services/Bookings.Infrastructure.Services.csproj
[VIH-4920](https://tools.hmcts.net/jira/browse/VIH-4920)
Updated vulnerable packages
```
[ ] Yes
[x] No
```
=> Updated vulnerable packages

BookingsAPI/Bookings.DAL/Migrations/20190821082431_addNewHearingCaseType.Designer.cs, BookingsAPI/Bookings.DAL/Migrations/20190821082431_addNewHearingCaseType.cs
https://tools.hmcts.net/jira/browse/VIH-4907
Inserted in the database new case type Hearing and insert records in Hearing Type, Case role
```
[ ] Yes
[X ] No
```
=> add new case type Hearing to database

BookingsAPI/Bookings.DAL/Commands/RemoveHearingCommand.cs
[VIH-4988](https://tools.hmcts.net/jira/browse/VIH-4988)
The delete hearing endpoint should remove all data. since the endpoint is used only by tests, it should clear 
```
[ ] Yes
[x] No
```
=> Removing a hearing should completely delete the data whereas

BookingsAPI/Bookings.DAL/Queries/GetBookingsByCaseTypesQuery.cs, BookingsAPI/Bookings.IntegrationTests/Database/Queries/GetBookingsByCaseTypesQueryHandlerTest.cs, BookingsAPI/Bookings.IntegrationTests/Helper/TestDataManager.cs
https://tools.hmcts.net/jira/browse/VIH-5063
Booking list include all record for today and future
```
[ X] Yes
[ ] No
```
=> Get booking list for today(any time today) and future

BookingsAPI/Bookings.DAL/Migrations/20191011082405_AddHearingTypesForCivilAndFinancial.Designer.cs, BookingsAPI/Bookings.DAL/Migrations/20191011082405_AddHearingTypesForCivilAndFinancial.cs
https://tools.hmcts.net/jira/browse/VIH-5079
```
[ ] Yes
[ ] No
```
=> VIH-5079: adding missing Hearing Types

BookingsAPI/Bookings.API/Controllers/HearingsController.cs, BookingsAPI/Bookings.API/Mappings/HearingToDetailResponseMapper.cs, BookingsAPI/Bookings.API/Mappings/VideoHearingToBookingsResponseMapper.cs, BookingsAPI/Bookings.AcceptanceTests/Models/CreateHearingRequestBuilder.cs, BookingsAPI/Bookings.AcceptanceTests/Models/UpdateHearingRequest.cs, BookingsAPI/Bookings.AcceptanceTests/Steps/HearingsSteps.cs, BookingsAPI/Bookings.Api.Contract/Requests/BookNewHearingRequest.cs, BookingsAPI/Bookings.Api.Contract/Requests/UpdateHearingRequest.cs, BookingsAPI/Bookings.Api.Contract/Responses/BookingsHearingResponse.cs, BookingsAPI/Bookings.Api.Contract/Responses/HearingDetailsResponse.cs, BookingsAPI/Bookings.DAL/Commands/CreateVideoHearingCommand.cs, BookingsAPI/Bookings.DAL/Commands/UpdateHearingCommand.cs, BookingsAPI/Bookings.DAL/Mappings/HearingMap.cs, BookingsAPI/Bookings.DAL/Migrations/20191127095013_Add_StreamingFlag.Designer.cs, BookingsAPI/Bookings.DAL/Migrations/20191127095013_Add_StreamingFlag.cs, BookingsAPI/Bookings.Domain/Hearing.cs, BookingsAPI/Bookings.IntegrationTests/Helper/TestDataManager.cs, BookingsAPI/Bookings.IntegrationTests/Steps/HearingsSteps.cs, BookingsAPI/Bookings.UnitTests/Controllers/HearingsControllerTest.cs, BookingsAPI/Bookings.UnitTests/Domain/Hearing/UpdateHearingDetailsTests.cs, BookingsAPI/Bookings.UnitTests/Mappings/HearingToDetailResponseMapperTests.cs, BookingsAPI/Bookings.UnitTests/Mappings/VideoHearingToBookingsResponseMapperTest.cs, BookingsAPI/Testing.Common/Builders/Domain/VideoHearingBuilder.cs
https://tools.hmcts.net/jira/browse/VIH-5340
Added new field StreamingFlag to Hearing
```
[X ] Yes
[ ] No
```
=> Added StreamingFlag field to Hearing

BookingsAPI/Bookings.API/Controllers/HearingsController.cs, BookingsAPI/Bookings.API/Mappings/HearingToDetailResponseMapper.cs, BookingsAPI/Bookings.API/Mappings/VideoHearingToBookingsResponseMapper.cs, BookingsAPI/Bookings.AcceptanceTests/Models/CreateHearingRequestBuilder.cs, BookingsAPI/Bookings.AcceptanceTests/Models/UpdateHearingRequest.cs, BookingsAPI/Bookings.AcceptanceTests/Steps/HearingsSteps.cs, BookingsAPI/Bookings.Api.Contract/Requests/BookNewHearingRequest.cs, BookingsAPI/Bookings.Api.Contract/Requests/UpdateHearingRequest.cs, BookingsAPI/Bookings.Api.Contract/Responses/BookingsHearingResponse.cs, BookingsAPI/Bookings.Api.Contract/Responses/HearingDetailsResponse.cs, BookingsAPI/Bookings.DAL/Commands/CreateVideoHearingCommand.cs, BookingsAPI/Bookings.DAL/Commands/UpdateHearingCommand.cs, BookingsAPI/Bookings.DAL/Mappings/HearingMap.cs, BookingsAPI/Bookings.DAL/Migrations/20191128133315_Remove_StreamingFlag.Designer.cs, BookingsAPI/Bookings.DAL/Migrations/20191128133315_Remove_StreamingFlag.cs, BookingsAPI/Bookings.Domain/Hearing.cs, BookingsAPI/Bookings.IntegrationTests/Helper/TestDataManager.cs, BookingsAPI/Bookings.IntegrationTests/Steps/HearingsSteps.cs, BookingsAPI/Bookings.UnitTests/Controllers/HearingsControllerTest.cs, BookingsAPI/Bookings.UnitTests/Domain/Hearing/UpdateHearingDetailsTests.cs, BookingsAPI/Bookings.UnitTests/Mappings/HearingToDetailResponseMapperTests.cs, BookingsAPI/Bookings.UnitTests/Mappings/VideoHearingToBookingsResponseMapperTest.cs, BookingsAPI/Testing.Common/Builders/Domain/VideoHearingBuilder.cs
Reversed task 5340
Removed Streaming flag field from 
```
[ X] Yes
[ ] No
```
=> reversed changes for streaming flag

BookingsAPI/Bookings.AcceptanceTests/Bookings.AcceptanceTests.csproj, BookingsAPI/Bookings.Infrastructure.Services/Bookings.Infrastructure.Services.csproj, BookingsAPI/Bookings.Infrastructure.Services/ServiceBusQueue/ServiceBusQueueClientFake.cs, BookingsAPI/Bookings.IntegrationTests/Bookings.IntegrationTests.csproj, BookingsAPI/Bookings.IntegrationTests/Contexts/TestContext.cs, BookingsAPI/Bookings.IntegrationTests/Helper/TestDataManager.cs, BookingsAPI/Bookings.IntegrationTests/Hooks/ApiHooks.cs, BookingsAPI/Bookings.IntegrationTests/Steps/HearingsSteps.cs, BookingsAPI/Bookings.IntegrationTests/Steps/ParticipantsSteps.cs, BookingsAPI/Bookings.IntegrationTests/Steps/SuitabilityAnswersSteps.cs, BookingsAPI/Bookings.UnitTests/Infrastructure.Services/IntegrationEventTests.cs
[VIH-5018](https://tools.hmcts.net/jira/browse/VIH-5018)
* Maintenance 
```
[ ] Yes
[x] No
```
=> Clean up additional data left behind after tests

BookingsAPI/Bookings.API/Controllers/HearingParticipantsController.cs, BookingsAPI/Bookings.API/Controllers/PersonsController.cs, BookingsAPI/Bookings.Infrastructure.Services/IntegrationEvents/Events/ParticipantUpdatedIntegrationEvent.cs, BookingsAPI/Bookings.UnitTests/Controllers/HearingParticipantsController/AddParticipantsToHearingTests.cs, BookingsAPI/Bookings.UnitTests/Controllers/HearingParticipantsController/UpdateParticipantDetailsTests.cs, BookingsAPI/Bookings.UnitTests/Controllers/Persons/GetPersonSuitabilityAnswersTests.cs
https://tools.hmcts.net/jira/browse/VIH-5604
Fix mutation and refactoring
```
[X ] Yes
[ ] No
```
=> VIH-5604 Fix mutation in unit tests and refactoring

.githooks/pre-commit, .githooks/prepare-commit-msg, BookingsAPI/Bookings.API/Controllers/HearingParticipantsController.cs, README.md
https://tools.hmcts.net/jira/browse/VIH-5605
add pre commit hook file
```
[X ] Yes
[ ] No
```
=> VIH 5605 pre commit git hook

BookingsAPI/Bookings.DAL/Migrations/20200321160307_UpdateJudgeGroupsForCaseTypes.Designer.cs, BookingsAPI/Bookings.DAL/Migrations/20200321160307_UpdateJudgeGroupsForCaseTypes.cs
https://tools.hmcts.net/jira/browse/VIH-5678
- update the group for judges to 0 for the new case types
```
[ ] Yes
[x] No
```
=> feature/VIH-5678 : Judge_status_not_showing_correct_display_name

BookingsAPI/Bookings.API/Controllers/HearingsController.cs, BookingsAPI/Bookings.API/Mappings/HearingToDetailResponseMapper.cs, BookingsAPI/Bookings.API/Mappings/VideoHearingToBookingsResponseMapper.cs, BookingsAPI/Bookings.AcceptanceTests/Models/CreateHearingRequestBuilder.cs, BookingsAPI/Bookings.AcceptanceTests/Models/UpdateHearingRequest.cs, BookingsAPI/Bookings.AcceptanceTests/Steps/HearingsSteps.cs, BookingsAPI/Bookings.Api.Contract/Requests/BookNewHearingRequest.cs, BookingsAPI/Bookings.Api.Contract/Requests/UpdateHearingRequest.cs, BookingsAPI/Bookings.Api.Contract/Responses/BookingsHearingResponse.cs, BookingsAPI/Bookings.Api.Contract/Responses/HearingDetailsResponse.cs, BookingsAPI/Bookings.DAL/Bookings.DAL.csproj, BookingsAPI/Bookings.DAL/Commands/CreateVideoHearingCommand.cs, BookingsAPI/Bookings.DAL/Commands/UpdateHearingCommand.cs, BookingsAPI/Bookings.DAL/Migrations/20200329115821_AddToHearingTableAudioRcordingField.Designer.cs, BookingsAPI/Bookings.DAL/Migrations/20200329115821_AddToHearingTableAudioRcordingField.cs, BookingsAPI/Bookings.Domain/Hearing.cs, BookingsAPI/Bookings.Domain/VideoHearing.cs, BookingsAPI/Bookings.IntegrationTests/Database/Commands/CreateVideoHearingCommandTests.cs, BookingsAPI/Bookings.IntegrationTests/Database/Commands/UpdateHearingCommandTests.cs, BookingsAPI/Bookings.IntegrationTests/Helper/TestDataManager.cs, BookingsAPI/Bookings.IntegrationTests/Steps/HearingsSteps.cs, BookingsAPI/Bookings.UnitTests/Controllers/HearingsController/HearingsControllerTest.cs, BookingsAPI/Bookings.UnitTests/Domain/Hearing/UpdateHearingDetailsTests.cs, BookingsAPI/Bookings.UnitTests/Domain/Hearing/ValidateArgumentsTests.cs, BookingsAPI/Bookings.UnitTests/Mappings/HearingToDetailResponseMapperTests.cs, BookingsAPI/Bookings.UnitTests/Mappings/VideoHearingToBookingsResponseMapperTest.cs, BookingsAPI/Testing.Common/Builders/Domain/VideoHearingBuilder.cs
https://tools.hmcts.net/jira/browse/VIH-5418
Added to hearing new field AudioRecordingRequired to indicate on/off audio recording
```
[ X] Yes
[ ] No
```
=> VIH-5418 added to hearing  new field audio recording required

BookingsAPI/Bookings.AcceptanceTests/Bookings.AcceptanceTests.csproj, BookingsAPI/Bookings.IntegrationTests/Bookings.IntegrationTests.csproj, BookingsAPI/Testing.Common/Testing.Common.csproj
https://tools.hmcts.net/jira/browse/VIH-5858
-Updated Acceptance test latest nuget reference to remove OWASPZAPDotNetAPI reference
```
[ ] Yes
[x] No
```
=> VIH-5858 Removed OWASPZAPDotNetAPI reference

BookingsAPI/Bookings.API/Controllers/HearingsController.cs, BookingsAPI/Bookings.UnitTests/Controllers/HearingsController/BookNewHearingTests.cs, BookingsAPI/Bookings.UnitTests/Controllers/HearingsController/GetHearingDetailsByIdTests.cs, BookingsAPI/Bookings.UnitTests/Controllers/HearingsController/GetHearingsByCaseNumberTests.cs, BookingsAPI/Bookings.UnitTests/Controllers/HearingsController/HearingsControllerTest.cs
https://tools.hmcts.net/jira/browse/VIH-5880
```
[ ] Yes
[ ] No
```
=> VIH-5880 Fix endpoint to url decode

BookingsAPI/Bookings.DAL/Queries/GetParticipantWithSuitabilityAnswersQuery.cs
https://tools.hmcts.net/jira/browse/VIH-5982
Fix infinity scrolling for suitability answers
```
[X] Yes
[ ] No
```
=> VIH-5982 fix get suitability answer

BookingsAPI/Bookings.DAL/Queries/GetHearingsByCaseNumberQuery.cs, BookingsAPI/Bookings.IntegrationTests/Database/Queries/GetHearingsByCaseNumberQueryHandlerDatabaseTests.cs, BookingsAPI/Bookings.IntegrationTests/Helper/TestDataManager.cs
https://tools.hmcts.net/jira/browse/VIH-5974
returns confirmed hearings for audio link
```
[ ] Yes
[ ] No
```
=> VIH-5974 return confirmed hearings for audio link

BookingsAPI/Bookings.API/Mappings/HearingByCaseNumberResponseMapper.cs, BookingsAPI/Bookings.DAL/Queries/GetHearingsByCaseNumberQuery.cs, BookingsAPI/Bookings.UnitTests/Mappings/HearingByCaseNumberResponseMapperTests.cs
https://tools.hmcts.net/jira/browse/VIH-6143
- modified query to trim spaces for the case number
```
[ ] Yes
[x] No
```
=> VIH-6143 Cannot_find_recorded_hearings_in_admin_web

BookingsAPI/Bookings.Api.Contract/Responses/PersonResponse.cs
https://tools.hmcts.net/jira/browse/VIH-5617
Remove address fields for Individual participants
```
[ ] Yes
[ ] No
```
=> VIH-5617 Removed address fields

BookingsAPI/Bookings.DAL/Commands/AnonymiseHearingsCommand.cs, BookingsAPI/Bookings.DAL/Queries/GetPersonsByClosedHearingsQuery.cs
https://tools.hmcts.net/jira/browse/VIH-6403
- exclude test accounts
```
[ ] Yes
[x] No
```
=> VIH-6403 Update gdpr job to exclude the test accounts

BookingsAPI/Bookings.API/Controllers/EndPointsController.cs, BookingsAPI/Bookings.API/Validations/UpdateEndpointRequestValidation.cs, BookingsAPI/Bookings.Api.Contract/Requests/UpdateEndpointRequest.cs, BookingsAPI/Bookings.DAL/Commands/UpdateEndPointOfHearingCommand.cs, BookingsAPI/Bookings.Domain/Endpoint.cs, BookingsAPI/Bookings.IntegrationTests/Database/Commands/UpdateEndPointOfHearingCommandTests.cs, BookingsAPI/Bookings.IntegrationTests/Features/Endpoints.feature, BookingsAPI/Bookings.IntegrationTests/Steps/EndPointSteps.cs, BookingsAPI/Bookings.UnitTests/Controllers/EndPointController/RemoveEndPointFromHearingTests.cs, BookingsAPI/Bookings.UnitTests/Controllers/EndPointController/UpdateDisplayNameForEndpointTests.cs, BookingsAPI/Bookings.UnitTests/Domain/EndPoints/UpdateDisplayNameTests.cs, BookingsAPI/Bookings.UnitTests/Validation/UpdateEndpointRequestValidationTests.cs, BookingsAPI/Testing.Common/Builders/Api/ApiUriFactory.cs
https://tools.hmcts.net/jira/browse/VIH-6330
Update display of an endpoint
```
[ ] Yes
[ x] No
```
=> VIH-6330 Update display of an endpoint

BookingsAPI/Bookings.DAL/Queries/GetPersonsByClosedHearingsQuery.cs
https://tools.hmcts.net/jira/browse/VIH-6429
- updated query to return distinct list of participants
```
[ ] Yes
[x] No
```
=> VIH-6429 GDPR_hot_fix_to_fix_query_timeout

BookingsAPI/Bookings.API/Controllers/EndPointsController.cs, BookingsAPI/Bookings.API/Controllers/HearingsController.cs, BookingsAPI/Bookings.API/Mappings/EndpointToResponseMapper.cs, BookingsAPI/Bookings.API/Mappings/HearingToDetailResponseMapper.cs, BookingsAPI/Bookings.AcceptanceTests/Bookings.AcceptanceTests.csproj, BookingsAPI/Bookings.Infrastructure.Services/Dtos/EndpointDto.cs, BookingsAPI/Bookings.Infrastructure.Services/Dtos/HearingDto.cs, BookingsAPI/Bookings.Infrastructure.Services/EndpointDtoMapper.cs, BookingsAPI/Bookings.Infrastructure.Services/IntegrationEvents/Events/EndpointAddedIntegrationEvent.cs, BookingsAPI/Bookings.Infrastructure.Services/IntegrationEvents/Events/EndpointRemovedIntegrationEvent.cs, BookingsAPI/Bookings.Infrastructure.Services/IntegrationEvents/Events/EndpointUpdatedIntegrationEvent.cs, BookingsAPI/Bookings.Infrastructure.Services/IntegrationEvents/Events/HearingDetailsUpdatedIntegrationEvent.cs, BookingsAPI/Bookings.Infrastructure.Services/IntegrationEvents/Events/HearingIsReadyForVideoIntegrationEvent.cs, BookingsAPI/Bookings.IntegrationTests/Database/Queries/GetPersonByOldHearings.cs, BookingsAPI/Bookings.IntegrationTests/Steps/CaseTypesSteps.cs, BookingsAPI/Bookings.UnitTests/Controllers/EndPointController/AddEndPointToHearingTests.cs, BookingsAPI/Bookings.UnitTests/Controllers/EndPointController/EndPointsControllerTests.cs, BookingsAPI/Bookings.UnitTests/Controllers/EndPointController/RemoveEndPointFromHearingTests.cs, BookingsAPI/Bookings.UnitTests/Controllers/EndPointController/UpdateDisplayNameForEndpointTests.cs, BookingsAPI/Bookings.UnitTests/Infrastructure.Services/IntegrationEventTests.cs
https://tools.hmcts.net/jira/browse/VIH-6348
=> VIH-6348 JVS endpoint_events

BookingsAPI/Bookings.DAL/Migrations/20200827154118_add_hearing_venues_for_court_of_appeal_criminal_division.Designer.cs, BookingsAPI/Bookings.DAL/Migrations/20200827154118_add_hearing_venues_for_court_of_appeal_criminal_division.cs
https://tools.hmcts.net/jira/browse/VIH-6244
- added new venues for cacd
```
[ ] Yes
[x] No
```
=> VIH-6244 Add_new_hearing_venues_for_CACD_hearings

BookingsAPI/Bookings.API/Controllers/PersonsController.cs, BookingsAPI/Bookings.API/Mappings/HearingToUsernameForDeletionResponseMapper.cs, BookingsAPI/Bookings.AcceptanceTests/Bookings.AcceptanceTests.csproj, BookingsAPI/Bookings.AcceptanceTests/Features/Persons.feature, BookingsAPI/Bookings.AcceptanceTests/Steps/PersonsSteps.cs, BookingsAPI/Bookings.Api.Contract/Responses/HearingsByUsernameForDeletionResponse.cs, BookingsAPI/Bookings.DAL/Queries/GetHearingsByUsernameForDeletionQuery.cs, BookingsAPI/Bookings.IntegrationTests/Bookings.IntegrationTests.csproj, BookingsAPI/Bookings.IntegrationTests/Database/Queries/GetHearingsByUsernameForDeletionQueryHandlerTests.cs, BookingsAPI/Bookings.IntegrationTests/Features/Persons.feature, BookingsAPI/Bookings.IntegrationTests/Steps/CommonSteps.cs, BookingsAPI/Bookings.IntegrationTests/Steps/PersonsSteps.cs, BookingsAPI/Bookings.UnitTests/Mappings/HearingToUsernameForDeletionResponseMapperTests.cs, BookingsAPI/Testing.Common/Builders/Api/ApiUriFactory.cs, BookingsAPI/Testing.Common/Configuration/TestData.cs, BookingsAPI/Testing.Common/Testing.Common.csproj
VIH-6412
get hearings by username for deletion
```
[ ] Yes
[x] No
```
=> VIH-6412 get hearings by username for deletion

BookingsAPI/Bookings.API/Controllers/PersonsController.cs, BookingsAPI/Bookings.DAL/Exceptions/PersonNotFoundException.cs, BookingsAPI/Bookings.DAL/Queries/GetHearingsByUsernameForDeletionQuery.cs, BookingsAPI/Bookings.IntegrationTests/Database/Queries/GetHearingsByUsernameForDeletionQueryHandlerTests.cs, BookingsAPI/Bookings.IntegrationTests/Features/Persons.feature, BookingsAPI/Bookings.IntegrationTests/Steps/PersonsSteps.cs
VIH-6412
Return a 404 status if username does not exist when searching for hearings
```
[ ] Yes
[x] No
```
=> VIH-6412 return not found when username does not exist

BookingsAPI/Bookings.API/Controllers/PersonsController.cs, BookingsAPI/Bookings.DAL/Commands/AnonymiseHearingsCommand.cs, BookingsAPI/Bookings.DAL/Commands/AnonymisePersonCommand.cs, BookingsAPI/Bookings.Domain/Person.cs, BookingsAPI/Bookings.IntegrationTests/Database/Commands/AnonymisePersonCommandTests.cs, BookingsAPI/Bookings.IntegrationTests/Features/Persons.feature, BookingsAPI/Bookings.IntegrationTests/Steps/PersonsSteps.cs, BookingsAPI/Bookings.UnitTests/Controllers/Persons/GetPersonByContactEmailTests.cs, BookingsAPI/Bookings.UnitTests/Controllers/Persons/GetPersonByUsernameTests.cs, BookingsAPI/Bookings.UnitTests/Controllers/Persons/GetPersonSuitabilityAnswersTests.cs, BookingsAPI/Bookings.UnitTests/Controllers/Persons/PersonsControllerTest.cs, BookingsAPI/Bookings.UnitTests/Controllers/Persons/PostPersonBySearchTermTests.cs, BookingsAPI/Bookings.UnitTests/Domain/Persons/AnonymisePersonTests.cs, BookingsAPI/Testing.Common/Builders/Api/ApiUriFactory.cs, CODEOWNERS
VIH-6413
Add patch endpoint to anonymise persons
```
[ ] Yes
[x] No
```
=> VIH-6413 add AnonymiseHearingsCommand.cs

BookingsAPI/Bookings.API/Controllers/HearingParticipantsController.cs
https://tools.hmcts.net/jira/browse/VIH-6469
- update to controller response.
```
[ ] Yes
[x] No
```
=> VIH-6469 unable_to_edit_a_booking

BookingsAPI/Bookings.DAL/Migrations/20200911124945_add_field_zipSuccess_to_hearing_table.Designer.cs, BookingsAPI/Bookings.DAL/Migrations/20200911124945_add_field_zipSuccess_to_hearing_table.cs, BookingsAPI/Bookings.Domain/Hearing.cs
https://tools.hmcts.net/jira/browse/VIH-6416
Add nullable Boolean field ZipSuccess to Hearing table
```
[ X] Yes
[ ] No
```
=> VIH-6416 Add zipSuccess field to Hearing

BookingsAPI/Bookings.API/Controllers/HearingsController.cs, BookingsAPI/Bookings.DAL/Commands/UpdateZipStatusCommand.cs, BookingsAPI/Bookings.IntegrationTests/Features/Hearings.feature, BookingsAPI/Bookings.IntegrationTests/Steps/HearingsSteps.cs, BookingsAPI/Bookings.UnitTests/Controllers/HearingsController/HearingsControllerTest.cs, BookingsAPI/Testing.Common/Builders/Api/ApiUriFactory.cs, BookingsAPI/Testing.Common/Configuration/TestData.cs
https://tools.hmcts.net/jira/browse/VIH-6417
endpoint to update audio recording zip status in hearing
```
[ X] Yes
[ ] No
```
=> VIH-6417 update audiorecording zip status

BookingsAPI/Bookings.API/Controllers/HearingsController.cs, BookingsAPI/Bookings.API/Validations/UpdateHearingRequestValidation.cs, BookingsAPI/Bookings.Api.Contract/Requests/UpdateHearingRequest.cs, BookingsAPI/Bookings.IntegrationTests/Steps/HearingsSteps.cs, BookingsAPI/Bookings.UnitTests/Controllers/HearingsController/HearingsControllerTest.cs, BookingsAPI/Bookings.UnitTests/Validation/UpdateHearingRequestValidationTests.cs
VIH-6525
Use existing hearing details when UpdateHearingRequest is null
```
[ ] Yes
[x] No
```
=> VIH-6525 handle nulls in update booking request

BookingsAPI/Bookings.API/Controllers/HearingsController.cs, BookingsAPI/Bookings.UnitTests/Controllers/HearingsController/HearingsControllerTest.cs, BookingsAPI/Bookings.UnitTests/Controllers/HearingsController/UpdateHearingDetailsTests.cs
VIH-6525
* Use updated hearing when sending message to queue for processing
```
[ ] Yes
[x] No
```
=> VIH-6525 update hearing details using wrong object

BookingsAPI/Bookings.DAL/Commands/RemoveEndPointFromHearingCommand.cs, BookingsAPI/Bookings.DAL/Commands/RemoveParticipantFromHearingCommand.cs, BookingsAPI/Bookings.Domain/Hearing.cs, BookingsAPI/Bookings.IntegrationTests/Database/Commands/RemoveEndPointFromHearingCommandTests.cs, BookingsAPI/Bookings.IntegrationTests/Database/Commands/RemoveParticipantFromHearingCommandTests.cs, BookingsAPI/Bookings.IntegrationTests/Helper/TestDataManager.cs
https://tools.hmcts.net/jira/browse/VIH-6554
- updated remove participant command
```
[ ] Yes
[x] No
```
=> VIH-6554 Bookings_Api-Failing_to_delete_hearings

BookingsAPI/Bookings.DAL/Mappings/EndpointMap.cs, BookingsAPI/Bookings.DAL/Mappings/HearingMap.cs, BookingsAPI/Bookings.DAL/Migrations/20200929102524_AddHearingIdForeignKeyForEndpoint.Designer.cs, BookingsAPI/Bookings.DAL/Migrations/20200929102524_AddHearingIdForeignKeyForEndpoint.cs, BookingsAPI/Bookings.Domain/Endpoint.cs, BookingsAPI/Bookings.UnitTests/Mappings/HearingToDetailResponseMapperTests.cs
https://tools.hmcts.net/jira/browse/VIH-6554
- update domain, added FK heaingid for endpoint table.
```
[ ] Yes
[x] No
```
=> VIH-6554 Failing_to_delete_hearings

azure-pipelines.yml
VIH-6594
update endpoint for pipeline
```
[ ] Yes
[x] No
```
=> VIH-6594 update endpoint for pipeline

BookingsAPI/Bookings.API/ConfigureServicesExtensions.cs, BookingsAPI/Bookings.API/Controllers/HearingsController.cs, BookingsAPI/Bookings.API/Startup.cs, BookingsAPI/Bookings.Common/ILogger.cs, BookingsAPI/Bookings.Common/Logger.cs, BookingsAPI/Bookings.UnitTests/Controllers/HearingsController/HearingsControllerTest.cs
https://tools.hmcts.net/jira/browse/VIH-6704
=> VIH-6704 Bookingsapi_logging

BookingsAPI/Bookings.DAL/Helper/CloneHearingToCommandMapper.cs, BookingsAPI/Bookings.UnitTests/Mappings/CloneHearingToCommandMapperTests.cs
https://tools.hmcts.net/jira/browse/VIH-6751
- set the 'QuestionnaireNotRequired' field to true for multi day hearings
```
[ ] Yes
[x] No
```
=> VIH-6751 Questionnaire_Not_Required_on_all_multi_day_bookings_does_not_match_the_selected_value

BookingsAPI/Bookings.DAL/BookingsDbContext.cs, BookingsAPI/Bookings.DAL/Commands/AnonymiseHearingsCommand.cs, BookingsAPI/Bookings.DAL/Mappings/JobHistoryMap.cs, BookingsAPI/Bookings.DAL/Migrations/20201110124414_AddJobHistory.Designer.cs, BookingsAPI/Bookings.DAL/Migrations/20201110124414_AddJobHistory.cs, BookingsAPI/Bookings.DAL/Queries/GetPersonsByClosedHearingsQuery.cs, BookingsAPI/Bookings.Domain/JobHistory.cs, BookingsAPI/Bookings.IntegrationTests/Database/Commands/AnonymiseHearingsCommandTests.cs, BookingsAPI/Bookings.IntegrationTests/Database/Queries/GetPersonByOldHearings.cs, BookingsAPI/Bookings.IntegrationTests/Helper/TestDataManager.cs
https://tools.hmcts.net/jira/browse/VIH-6709
gdpr timeout issue
```
[ ] Yes
[x ] No
```
=> VIH-6709 Gdpr timeout issue

BookingsAPI/Bookings.API/Mappings/VideoHearingToBookingsResponseMapper.cs, BookingsAPI/Bookings.Api.Contract/Responses/BookingsHearingResponse.cs, BookingsAPI/Bookings.DAL/Commands/AnonymiseHearingsCommand.cs, BookingsAPI/Bookings.UnitTests/Mappings/VideoHearingToBookingsResponseMapperTest.cs
https://tools.hmcts.net/jira/browse/VIH-6723
- added courtroom account  to hearing response.
```
[ ] Yes
[x] No
```
=> VIH-6723 VHO_sees_courtroom_account_in_Booking_List

BookingsAPI/Bookings.API/Controllers/HearingsController.cs, BookingsAPI/Bookings.API/Startup.cs, BookingsAPI/Bookings.Infrastructure.Services/ServiceBusQueue/ServiceBusQueueClient.cs
https://tools.hmcts.net/jira/browse/VIH-6711
=> VIH-6711  STOP reties on ServiceBus for Create Booking

BookingsAPI/Bookings.Infrastructure.Services/ServiceBusQueue/ServiceBusQueueClient.cs
https://tools.hmcts.net/jira/browse/VIH-6711
=> VIH-6711 revert_queue_retry

BookingsAPI/Bookings.AcceptanceTests/Features/CaseTypes.feature, BookingsAPI/Bookings.DAL/Migrations/20201218135520_AddMissingCaseRoleForImmigration.Designer.cs, BookingsAPI/Bookings.DAL/Migrations/20201218135520_AddMissingCaseRoleForImmigration.cs, BookingsAPI/Bookings.IntegrationTests/Features/CaseTypes.feature
https://tools.hmcts.net/jira/browse/VIH-6738
=> VIH-6738 missing judge case role for Immigration and Asylum

.gitignore, BookingsAPI/Bookings.AcceptanceTests/Bookings.AcceptanceTests.csproj, BookingsAPI/Bookings.AcceptanceTests/Configuration/AcceptanceTestConfiguration.cs, BookingsAPI/Bookings.AcceptanceTests/Contexts/TestContext.cs, BookingsAPI/Bookings.AcceptanceTests/Hooks/HealthCheckHooks.cs, BookingsAPI/Bookings.AcceptanceTests/Hooks/RemoveDataHooks.cs, BookingsAPI/Bookings.AcceptanceTests/Steps/CaseTypesSteps.cs, BookingsAPI/Bookings.AcceptanceTests/Steps/CommonSteps.cs, BookingsAPI/Bookings.AcceptanceTests/Steps/EndPointsSteps.cs, BookingsAPI/Bookings.AcceptanceTests/Steps/HealthCheckSteps.cs, BookingsAPI/Bookings.AcceptanceTests/Steps/HearingVenuesSteps.cs, BookingsAPI/Bookings.AcceptanceTests/Steps/HearingsSteps.cs, BookingsAPI/Bookings.AcceptanceTests/Steps/ParticipantsSteps.cs, BookingsAPI/Bookings.AcceptanceTests/Steps/PersonsSteps.cs, BookingsAPI/Bookings.IntegrationTests/Bookings.IntegrationTests.csproj, BookingsAPI/Bookings.IntegrationTests/Hooks/RemoveDataHooks.cs, BookingsAPI/Bookings.IntegrationTests/Steps/CaseTypesSteps.cs, BookingsAPI/Bookings.IntegrationTests/Steps/CloneHearingSteps.cs, BookingsAPI/Bookings.IntegrationTests/Steps/EndPointSteps.cs, BookingsAPI/Bookings.IntegrationTests/Steps/HearingVenueSteps.cs, BookingsAPI/Bookings.IntegrationTests/Steps/HearingsSteps.cs, BookingsAPI/Bookings.IntegrationTests/Steps/ParticipantsSteps.cs, BookingsAPI/Bookings.IntegrationTests/Steps/PersonsSteps.cs, BookingsAPI/Bookings.IntegrationTests/Steps/SearchHearingSteps.cs, BookingsAPI/Bookings.IntegrationTests/Steps/SuitabilityAnswersSteps.cs, BookingsAPI/Bookings.UnitTests/Domain/Hearing/UpdateStatusTest.cs
- Fix failing booking api build
- Upgrade packages
- Fixed failing unit tess
```
[ ] Yes
[X] No
```
=> VIH-5255 Fixed AC and Integration tests

BookingsAPI/Bookings.API/Controllers/CaseTypesController.cs, BookingsAPI/Bookings.AcceptanceTests/Steps/CaseTypesSteps.cs, BookingsAPI/Bookings.Api.Contract/Responses/CaseRoleResponse.cs, BookingsAPI/Bookings.Api.Contract/Responses/HearingRoleResponse.cs, BookingsAPI/Bookings.IntegrationTests/Steps/CaseTypesSteps.cs, BookingsAPI/Bookings.UnitTests/Controllers/CaseTypes/GetHearingRolesForCaseRoleTests.cs
https://tools.hmcts.net/jira/browse/VIH-6923
=> VIH-6923 Add the UserRole to the hearing role

BookingsAPI/Bookings.API/Controllers/EndPointsController.cs, BookingsAPI/Bookings.API/Controllers/HearingsController.cs, BookingsAPI/Bookings.API/Helpers/HearingControlLogHelper.cs, BookingsAPI/Bookings.API/Mappings/AudioRecordedHearingsBySearchResponseMapper.cs, BookingsAPI/Bookings.API/Mappings/HearingToUsernameForDeletionResponseMapper.cs, BookingsAPI/Bookings.API/Mappings/VideoHearingToBookingsResponseMapper.cs, BookingsAPI/Bookings.API/Validations/UpdateBookingStatusRequestValidation.cs, BookingsAPI/Bookings.UnitTests/.config/dotnet-tools.json, BookingsAPI/Bookings.UnitTests/Controllers/EndPointController/AddEndPointToHearingTests.cs, BookingsAPI/Bookings.UnitTests/Controllers/EndPointController/RemoveEndPointFromHearingTests.cs, BookingsAPI/Bookings.UnitTests/Controllers/EndPointController/UpdateEndpointTests.cs, BookingsAPI/Bookings.UnitTests/Controllers/HearingsController/BookNewHearingTests.cs, BookingsAPI/Bookings.UnitTests/Controllers/HearingsController/CloneHearingTests.cs, BookingsAPI/Bookings.UnitTests/Controllers/HearingsController/HearingsControllerTests.cs, BookingsAPI/Bookings.UnitTests/Helpers/HearingControlLogHelperTests.cs, BookingsAPI/Bookings.UnitTests/Mappings/AudioRecordedHearingsBySearchResponseMapperTests.cs, BookingsAPI/Bookings.UnitTests/Mappings/EndpointToResponseMapperTests.cs, BookingsAPI/Bookings.UnitTests/Mappings/HearingToUsernameForDeletionResponseMapperTests.cs, BookingsAPI/Bookings.UnitTests/Mappings/VideoHearingToBookingsResponseMapperTest.cs, BookingsAPI/Bookings.UnitTests/Validation/CloneHearingRequestValidationTests.cs, BookingsAPI/Bookings.UnitTests/stryker-config.json
https://tools.hmcts.net/jira/browse/VIH-5604
- Fix mutation issues
- 
```
[ ] Yes
[x] No
```
=> VIH-5604 Mutation issue fixes

BookingsAPI/Bookings.AcceptanceTests/Bookings.AcceptanceTests.csproj, BookingsAPI/Bookings.AcceptanceTests/Hooks/ConfigHooks.cs, BookingsAPI/Bookings.AcceptanceTests/parameters.runsettings, BookingsAPI/Bookings.IntegrationTests/Bookings.IntegrationTests.csproj, BookingsAPI/Testing.Common/Testing.Common.csproj
https://tools.hmcts.net/jira/browse/VIH-7058
- Enabling local test environment switching
```
[ ] Yes
[X] No
```
=> VIH-7058 Enabling local test environment switching

.gitignore, BookingsAPI/Bookings.API/Bookings.API.csproj, BookingsAPI/Bookings.API/Dockerfile, BookingsAPI/Bookings.API/Program.cs, BookingsAPI/nuget.config
VIH-7171
Add config provider to allow migration to the new SDS environments.
Docker build test
https://hmctsreform.visualstudio.com/VirtualHearings/_build/results?buildId=27878&view=logs&j=275f1d19-1bd8-5591-b06b-07d489ea915a&t=275f1d19-1bd8-5591-b06b-07d489ea915a
```
[ ] Yes
[X] No
```
=> VIH-7171 added configuration provider

BookingsApi/BookingsApi.IntegrationTests/Features/Participants.feature
VIH-6162
add a positive scenario for participant updated
```
[ ] Yes
[x] No
```
=> VIH-6162 add a positive scenario for participant updated

BookingsApi/BookingsApi.AcceptanceTests/packages.lock.json, BookingsApi/BookingsApi.IntegrationTests/packages.lock.json, BookingsApi/BookingsApi.UnitTests/packages.lock.json, BookingsApi/BookingsApi/BookingsApi.csproj, BookingsApi/BookingsApi/Program.cs, BookingsApi/BookingsApi/packages.lock.json
VIH-7171
Update usage of AddAksKeyVaultSecretProvider
```
[ ] Yes
[x] No
```
=> VIH-7171 Update usage of AddAksKeyVaultSecretProvider

BookingsApi/BookingsApi/Controllers/PersonsController.cs
VIH-6637
Do not update anonymised hearings
```
[ ] Yes
[x] No
```
=> VIH-6637 Do not update anonymised hearings

azure-pipelines.release.yml
- Added test3 env
```
[ ] Yes
[X] No
```
=> VIH-5552 Added test3 env

BookingsApi/BookingsApi.UnitTests/Controllers/Persons/UpdatePersonDetailsTests.cs, BookingsApi/BookingsApi/Controllers/PersonsController.cs, BookingsApi/Testing.Common/Builders/Domain/VideoHearingBuilder.cs
VIH-6162
* optimise the filter for participants to update when personal details have been updated
* ignore anonymised hearings and anonymised participants
```
[ ] Yes
[x] No
```
=> VIH-6162 optimise the filter for participants to update

BookingsApi/BookingsApi.Infrastructure.Services/Dtos/LinkedParticipantDto.cs, BookingsApi/BookingsApi.Infrastructure.Services/Dtos/ParticipantDto.cs, BookingsApi/BookingsApi.Infrastructure.Services/IntegrationEvents/Events/ParticipantsAddedIntegrationEvent.cs, BookingsApi/BookingsApi.Infrastructure.Services/LinkedParticipantDtoMapper.cs, BookingsApi/BookingsApi.Infrastructure.Services/ParticipantDtoMapper.cs, BookingsApi/BookingsApi.UnitTests/Mappings/IntegrationDtoMapperTests.cs, BookingsApi/BookingsApi.UnitTests/Mappings/LinkedParticipantDtoMapperTests.cs, BookingsApi/BookingsApi/ConfigureServicesExtensions.cs, BookingsApi/BookingsApi/Controllers/HearingParticipantsController.cs
VIH-6967
Updated integration events for add, update and remove participant with linked participant support for existing hearing
```
[ ] Yes
[x] No
```
=> VIH-6967 HearingsParticipantController updated to support LinkedParticipants

BookingsApi/BookingsApi/Dockerfile
=> VIH-7234 Fixing typo

BookingsApi/BookingsApi.DAL/BookingsApi.DAL.csproj, BookingsApi/BookingsApi.DAL/Migrations/20210129121439_AddLinkedParticipantTable.Designer.cs, BookingsApi/BookingsApi.DAL/Migrations/20210210112405_UpdateInterpreterHearingRole.Designer.cs, BookingsApi/BookingsApi.DAL/Migrations/20210210112405_UpdateInterpreterHearingRole.cs, BookingsApi/BookingsApi.DAL/Migrations/BookingsDbContextModelSnapshot.cs
https://tools.hmcts.net/jira/browse/VIH-7214
- fixed trailing space in the hearing role name for interpreter
```
[ ] Yes
[x] No
```
=> VIH-7214 update hearing role interpreter

BookingsApi/BookingsApi.AcceptanceTests/specflow.json, BookingsApi/BookingsApi.Client/BookingsApiClient.cs, BookingsApi/BookingsApi.IntegrationTests/Steps/SearchForPersonSteps.cs, BookingsApi/BookingsApi.IntegrationTests/specflow.json, BookingsApi/BookingsApi/Controllers/PersonsController.cs
VIH-6162
Allow JOHs to be searched for edit
```
[ ] Yes
[x] No
```
=> VIH-6162 Allow JOHs to be searched for edit

BookingsApi/BookingsApi.Common/Configuration/SettingsConfiguration.cs, BookingsApi/BookingsApi/Startup.cs
https://tools.hmcts.net/jira/browse/VIH-7258
added https config setting and startup check
```
[ ] Yes
[ x] No
```
=> VIH-7258 added https config setting and startup check

BookingsApi/BookingsApi.DAL/Dtos/LinkedParticipantDto.cs, BookingsApi/BookingsApi.DAL/Helper/CloneHearingToCommandMapper.cs, BookingsApi/BookingsApi.Infrastructure.Services/ServiceBusQueue/ServiceBusQueueClientFake.cs, BookingsApi/BookingsApi.IntegrationTests/Database/Commands/AddParticipantsToVideoHearingCommandTests.cs, BookingsApi/BookingsApi.IntegrationTests/Database/Commands/CreateVideoHearingCommandTests.cs, BookingsApi/BookingsApi.IntegrationTests/Database/Commands/UpdateParticipantCommandTests.cs, BookingsApi/BookingsApi/Mappings/LinkedParticipantRequestToLinkedParticipantDtoMapper.cs
VIH-6958 
* add ctor to LinkedParticipantDto.cs to ensure all values are provided
```
[ ] Yes
[x] No
```
=> VIH-6958 ensure dtos are mapped for BQS

BookingsApi/BookingsApi.Infrastructure.Services/Dtos/HearingDto.cs, BookingsApi/BookingsApi.Infrastructure.Services/HearingDtoMapper.cs, BookingsApi/BookingsApi.IntegrationTests/Steps/HearingsSteps.cs, BookingsApi/BookingsApi.UnitTests/Controllers/HearingsController/HearingsControllerTests.cs, BookingsApi/BookingsApi.UnitTests/Controllers/HearingsController/UpdateHearingDetailsTests.cs, BookingsApi/BookingsApi.UnitTests/Mappings/IntegrationDtoMapperTests.cs
VIH-6540
Add group id to BQS DTO
```
[ ] Yes
[x] No
```
=> VIH-6540 Add group id to BQS DTO

BookingsApi/BookingsApi.AcceptanceTests/Features/Participants.feature, BookingsApi/BookingsApi.AcceptanceTests/Models/CreateHearingRequestBuilder.cs, BookingsApi/BookingsApi.AcceptanceTests/Models/UpdateParticipantRequest.cs, BookingsApi/BookingsApi.AcceptanceTests/Steps/CommonSteps.cs, BookingsApi/BookingsApi.AcceptanceTests/Steps/ParticipantsSteps.cs
https://tools.hmcts.net/jira/browse/VIH-6895
- Updated linkedparticipant AC scenarios
```
[ ] Yes
[x] No
```
=> VIH-6895 Updated AC scenarios with linkedparticipants

BookingsApi/BookingsApi.AcceptanceTests/packages.lock.json, BookingsApi/BookingsApi.IntegrationTests/packages.lock.json, BookingsApi/BookingsApi.UnitTests/packages.lock.json, BookingsApi/BookingsApi/BookingsApi.csproj, BookingsApi/BookingsApi/ConfigureServicesExtensions.cs, BookingsApi/BookingsApi/packages.lock.json
- Fix for Swagger
```
[ ] Yes
[X] No
```
=> VIH-5552 Fix for Swagger

BookingsApi/BookingsApi.DAL/Queries/GetPersonsByClosedHearingsQuery.cs, BookingsApi/BookingsApi.IntegrationTests/Database/Commands/AnonymiseHearingsCommandTests.cs, BookingsApi/BookingsApi.IntegrationTests/Database/Queries/GetPersonByOldHearings.cs, BookingsApi/BookingsApi.IntegrationTests/Helper/TestDataManager.cs, BookingsApi/BookingsApi.IntegrationTests/Steps/PersonsSteps.cs
https://tools.hmcts.net/jira/browse/VIH-7469
- updated the query to include joh participants for anonymisation.
```
[ ] Yes
[x] No
```
=> VIH-7469 GDPR_script_is_not_anonymizing_JOH_users 

BookingsApi/BookingsApi.DAL/Commands/RemoveHearingCommand.cs
https://tools.hmcts.net/jira/browse/VIH-7465
- added check to prevent removal of person records if participant exists in another hearing.
```
[ ] Yes
[x] No
```
=> VIH-7465 remove hearing

BookingsApi/BookingsApi.DAL/Queries/BaseQueries/VideoHearings.cs, BookingsApi/BookingsApi.DAL/Queries/GetHearingsByGroupIdQuery.cs, BookingsApi/BookingsApi.DAL/Queries/GetHearingsByUsernameQuery.cs
https://tools.hmcts.net/jira/browse/VIH-7465
- update vh base query to iqueryable.
```
[ ] Yes
[x] No
```
=> VIH-7465 Remove-Hearing-Timeout-Error 

BookingsApi/BookingsApi.Client/BookingsApiClient.cs, BookingsApi/BookingsApi.DAL/Queries/GetJudiciaryPersonBySearchTermQuery.cs, BookingsApi/BookingsApi.UnitTests/Controllers/JudiciaryPersonControllerTests.cs, BookingsApi/BookingsApi.UnitTests/DAL/Queries/GetJudiciaryPersonBySearchTermQueryTest.cs, BookingsApi/BookingsApi.UnitTests/Mappings/JudiciaryPersonToResponseMapperTest.cs, BookingsApi/BookingsApi/Controllers/JudiciaryPersonController.cs, BookingsApi/BookingsApi/Mappings/JudiciaryPersonToResponseMapper.cs
https://tools.hmcts.net/jira/browse/VIH-7528
added search by term of email the judiciary person
```
[ X] Yes
[ ] No
```
=> VIH-7528 added search by term for judiciary person

BookingsApi/BookingsApi.Contract/Requests/JudiciaryPersonRequest.cs, BookingsApi/BookingsApi.DAL/Commands/AddJudiciaryPersonCommand.cs, BookingsApi/BookingsApi.DAL/Commands/JudiciaryPersonCommandBase.cs, BookingsApi/BookingsApi.DAL/Commands/UpdateJudiciaryPersonByExternalRefIdCommand.cs, BookingsApi/BookingsApi.DAL/Migrations/20210329113704_add_has_left_to_judiacary_person_table.Designer.cs, BookingsApi/BookingsApi.DAL/Migrations/20210329113704_add_has_left_to_judiacary_person_table.cs, BookingsApi/BookingsApi.Domain/JudiciaryPerson.cs, BookingsApi/BookingsApi.IntegrationTests/Database/Commands/AddJudiciaryPersonCommandTests.cs, BookingsApi/BookingsApi.IntegrationTests/Database/Commands/UpdateJudiciaryPersonByExternalRefIdCommandTests.cs, BookingsApi/BookingsApi.UnitTests/Controllers/JudiciaryPersonControllerTests.cs, BookingsApi/BookingsApi.UnitTests/Domain/JudiciaryPersons/UpdateJudiciaryPersonTests.cs, BookingsApi/BookingsApi/Controllers/JudiciaryPersonController.cs, BookingsApi/Testing.Common/Builders/Domain/JudiciaryPersonBuilder.cs
https://tools.hmcts.net/jira/browse/VIH-7407
=> VIH-7407 Add HasLeft Prop to ejudiciaryPerson

BookingsApi/BookingsApi.Domain/BookingStatusTransition.cs, BookingsApi/BookingsApi.IntegrationTests/Database/Commands/UpdateHearingStatusCommandTests.cs, BookingsApi/BookingsApi.UnitTests/Domain/Hearing/UpdateStatusTest.cs
VIH-7650
* Update booking status transition model so status can move from Failed to Confirmed 
* Enable retry confirmation of failed bookings
```
[ ] Yes
[x] No
```
=> VIH-7650 retry confirmation of failed bookings

azure-pipelines.release.yml, azure-pipelines.yml
VIH-7660
Change PAT token for AZDO
```
[ ] Yes
[X] No
```
=> VIH-7660 - updated PAT

BookingsApi/BookingsApi.Client/BookingsApiClient.cs, BookingsApi/BookingsApi.Contract/Requests/UpdateHearingParticipantsRequest.cs, BookingsApi/BookingsApi.Contract/Requests/UpdateParticipantRequest.cs, BookingsApi/BookingsApi.DAL/Commands/RemoveParticipantFromHearingCommand.cs, BookingsApi/BookingsApi.DAL/Commands/UpdateHearingParticipantsCommand.cs, BookingsApi/BookingsApi.Infrastructure.Services/IntegrationEvents/Events/HearingParticipantsUpdatedIntegrationEvent.cs, BookingsApi/BookingsApi.Infrastructure.Services/IntegrationEvents/Events/ParticipantsAddedIntegrationEvent.cs, BookingsApi/BookingsApi.IntegrationTests/Database/Commands/UpdateHearingParticipantsCommandHandlerTests.cs, BookingsApi/BookingsApi.UnitTests/Controllers/HearingParticipantsController/UpdateHearingParticipantsTests.cs, BookingsApi/BookingsApi.UnitTests/Validation/UpdateHearingParticipantsRequestValidationTests.cs, BookingsApi/BookingsApi/Controllers/HearingParticipantsController.cs, BookingsApi/BookingsApi/Validations/UpdateHearingParticipantsRequestValidation.cs
https://tools.hmcts.net/jira/browse/VIH-7766
Created a new endpoint and command which updates a hearing's participants.
```
[ ] Yes
[ x ] No
```
=> VIH-7766 Create Endpoint which takes in a full list of participants and updates the hearing with them

BookingsApi/BookingsApi.DAL/Commands/HearingService.cs
https://tools.hmcts.net/jira/browse/VIH-7696
- Check the person exist in person table by either user name or contact email.
```
[ ] Yes
[x] No
```
=> VIH-7696 check the person does exist in the table or not by username or email

BookingsApi/BookingsApi.UnitTests/Controllers/JudiciaryPersonControllerTests.cs, BookingsApi/BookingsApi/Controllers/JudiciaryPersonController.cs
https://tools.hmcts.net/jira/browse/VIH-7939
Mask Mask retrieval of EJud persons from Bookings API, till we do a complete Release 1.27
```
[ ] Yes
[X] No
```
=> VIH-7939 Mask retrieval of EJud persons from Bookings API 

BookingsApi/BookingsApi.UnitTests/Controllers/JudiciaryPersonControllerTests.cs, BookingsApi/BookingsApi/Controllers/JudiciaryPersonController.cs
https://tools.hmcts.net/jira/browse/VIH-7943
VIH-7943 Unmask EJud Retrieval with full list
```
[ ] Yes
[X] No
```
=> VIH-7943 Unmask EJud Retrieval with full list

BookingsApi/BookingsApi.DAL/Queries/GetPersonBySearchTermQuery.cs, BookingsApi/BookingsApi.IntegrationTests/Database/Queries/GetPersonBySearchTermQueryHandlerEFCoreTests.cs
https://tools.hmcts.net/jira/browse/VIH-7978
- on the updated query the reference to the organisation table was missed
**Does this PR introduce a breaking change?** 
```
[ ] Yes
[x] No
```
=> VIH-7978 - included organisation in the search query which was missed

BookingsApi/BookingsApi.DAL/Queries/GetPersonBySearchTermQuery.cs, BookingsApi/BookingsApi.IntegrationTests/Database/Queries/GetPersonBySearchTermQueryHandlerEFCoreTests.cs
https://tools.hmcts.net/jira/browse/VIH-7978
```
[ ] Yes
[x ] No
```
=> VIH-7978 - Removed duplication in participant search..

BookingsApi/BookingsApi.DAL/Helper/UserRoleForHearingRole.cs, BookingsApi/BookingsApi.DAL/Helper/UserRoles.cs, BookingsApi/BookingsApi.DAL/Migrations/20210813101442_AddInterpreterRoleForGRCEJ.Designer.cs, BookingsApi/BookingsApi.DAL/Migrations/20210813101442_AddInterpreterRoleForGRCEJ.cs
https://tools.hmcts.net/jira/browse/VIH-8107
- adding missing role for grc ej
**Does this PR introduce a breaking change?** 
```
[ ] Yes
[x] No
```
=> VIH-8107 added missing role for grc ej case type

BookingsApi/BookingsApi.Client/BookingsApiClient.cs, BookingsApi/BookingsApi.DAL/Queries/GetStaffMemberBySearchTermQuery.cs, BookingsApi/BookingsApi.IntegrationTests/Database/Queries/GetStaffMemberBySearchTermQueryHandlerDatabaseTests.cs, BookingsApi/BookingsApi.UnitTests/Controllers/StaffMemberControllerTests.cs, BookingsApi/BookingsApi/Controllers/StaffMemberController.cs
https://tools.hmcts.net/jira/browse/VIH-8034
- Ability to search staff member only
```
[ ] Yes
[x] No
```
=> VIH-8034 Search existing staff members

BookingsApi/BookingsApi.DAL/Commands/UpdateHearingParticipantsCommand.cs, BookingsApi/BookingsApi.Domain/Hearing.cs, BookingsApi/BookingsApi.UnitTests/Domain/Hearing/RemoveParticipantTests.cs, BookingsApi/BookingsApi.UnitTests/Domain/Hearing/ValidateHostCountTests.cs
https://tools.hmcts.net/jira/browse/VIH-8375
=> VIH-8375 Allow bookings with only a host present

BookingsApi/BookingsApi.AcceptanceTests/BookingsApi.AcceptanceTests.csproj, BookingsApi/BookingsApi.AcceptanceTests/packages.lock.json, BookingsApi/BookingsApi.DAL/BookingsApi.DAL.csproj, BookingsApi/BookingsApi.DAL/packages.lock.json, BookingsApi/BookingsApi.IntegrationTests/BookingsApi.IntegrationTests.csproj, BookingsApi/BookingsApi.IntegrationTests/appsettings.json, BookingsApi/BookingsApi.IntegrationTests/packages.lock.json, BookingsApi/BookingsApi.UnitTests/BookingsApi.UnitTests.csproj, BookingsApi/BookingsApi.UnitTests/packages.lock.json, BookingsApi/BookingsApi/BookingsApi.csproj, BookingsApi/BookingsApi/packages.lock.json
VIH-8687
- updating package reference for sql client to allow specifying command timeout in connection string
```
[ ] Yes
[x] No
```
=> VIH-8687 update command execution timeout

BookingsApi/BookingsApi.AcceptanceTests/Features/EndPoints.feature, BookingsApi/BookingsApi.Client/BookingsApiClient.cs, BookingsApi/BookingsApi.IntegrationTests/Features/Endpoints.feature, BookingsApi/BookingsApi.UnitTests/Controllers/EndPointController/AddEndPointToHearingTests.cs, BookingsApi/BookingsApi/Controllers/EndPointsController.cs
https://tools.hmcts.net/jira/browse/VIH-8568
- updated endpoints controller to return endpoints response object
```
[ ] Yes
[x] No
```
=> VIH-8568 changed api contract for endpoints controller

BookingsApi/BookingsApi.Client/BookingsApiClient.cs, BookingsApi/BookingsApi.DAL/Queries/GetBookingsByCaseTypesQuery.cs, BookingsApi/BookingsApi.IntegrationTests/Database/Queries/GetBookingsByCaseTypesQueryHandlerTest.cs, BookingsApi/BookingsApi.IntegrationTests/Helper/SeedVideoHearingOptions.cs, BookingsApi/BookingsApi.IntegrationTests/Helper/TestDataManager.cs, BookingsApi/BookingsApi.UnitTests/Controllers/HearingsController/HearingsControllerTests.cs, BookingsApi/BookingsApi/Controllers/HearingsController.cs
https://tools.hmcts.net/jira/browse/VIH-8797
Adds query parameter to the bookings API endpoint to be able to search by venues.
```
[ ] Yes
[x] No
```
=> VIH-8797 Add functionality to search bookings by venue

BookingsApi/BookingsApi.Client/BookingsApiClient.cs, BookingsApi/BookingsApi.DAL/Queries/GetBookingsByCaseTypesQuery.cs, BookingsApi/BookingsApi.IntegrationTests/Database/Queries/GetBookingsByCaseTypesQueryHandlerTest.cs, BookingsApi/BookingsApi.UnitTests/Controllers/HearingsController/HearingsControllerTests.cs, BookingsApi/BookingsApi/Controllers/HearingsController.cs
https://tools.hmcts.net/jira/browse/VIH-8743
```
[ ] Yes
[ x] No
```
=> VIH-8743 Changed for Search start date and end dates.

BookingsApi/BookingsApi.Contract/Enums/CaseRoleGroup.cs
https://tools.hmcts.net/jira/browse/VIH-8803
- add missing case roles from contract
```
[ ] Yes
[x] No
```
=> VIH-8803 add missing case roles from contract

charts/vh-bookings-api/Chart.yaml
=> VIH-7590 updated Chart version

BookingsApi/BookingsApi.DAL/Migrations/20220404133446_RemoveLocalAuthorityRoleForEmploymentAppealTribunal.cs
https://tools.hmcts.net/jira/browse/VIH-8891
Fixes an issue with a previous migration. Set the live flag to false instead of deleting the hearing role
```
[ ] Yes
[x ] No
```
=> VIH-8891 Update migration to use live flag instead of delete

BookingsApi/BookingsApi.Client/BookingsApiClient.cs, BookingsApi/BookingsApi.DAL/Queries/GetHearingsForNotificationsQuery.cs, BookingsApi/BookingsApi.IntegrationTests/Database/Queries/GetHearingsForNotificationsQueryHandlerTests.cs, BookingsApi/BookingsApi.UnitTests/Controllers/HearingsController/GetHearingsForNotificationTests.cs, BookingsApi/BookingsApi/Controllers/HearingsController.cs
https://tools.hmcts.net/jira/browse/VIH-7318
```
[ ] Yes
[ x] No
```
=> VIH-7318 Notify hearing reminder email changes

azure-pipelines.sds.pr-release.yml
[VIH-8963](https://tools.hmcts.net/jira/browse/VIH-8963)
Change PR tagging on docker images for Bookings API
```
[ ] Yes
[ x ] No
```
=> VIH-8963 - Change PR Tagging Solution

azure-pipelines.sds.release.yml, variables/production.yaml, variables/shared.yaml, variables/staging.yaml
VIH-8045
Create a release pipeline to trigger for non-prod and prod.
```
[ ] Yes
[ x ] No
```
=> VIH-8045 Release Pipeline

charts/vh-bookings-api/values.dev.template.yaml, charts/vh-bookings-api/values.yaml
Update the Charts Data
```
[ ] Yes
[ x ] No
```
=> Update the Charts Data

BookingsApi/BookingsApi/Dockerfile, azure-pipelines.sds.pr-release.yml, azure-pipelines.sds.release.yml
(VIH-8951)[https://tools.hmcts.net/jira/browse/VIH-8951]
update VH bookings API docker image.
```
[ ] Yes
[ X ] No
```
=> VIH-8951 - Update VH Bookings API Docker Image

azure-pipelines.sds.pr-close.yml, azure-pipelines.sds.pr-release.yml, variables/shared.yaml
VIH-8964
Check the active cluster before running commands
```
[ ] Yes
[ x ] No
```
=> VIH-8964 - Check active cluster before running pipeline

azure-pipelines.sds.pr-release.yml
[VIH-8958](https://tools.hmcts.net/jira/browse/VIH-8958)
Update DNS for VH Bookings Api.
```
[ ] Yes
[ X ] No
```
=> VIH-8958 - Update DNS

azure-pipelines.sds.release.yml, variables/production.yaml, variables/shared.yaml, variables/staging.yaml
VIH-8960
update SDS release Pipeline for Prod & Staging.
```
[ ] Yes
[X ] No
```
=> VIH-8960 - Amend SDS Release Pipeline Bookings API

azure-pipelines.sds.pr-release.yml, charts/vh-bookings-api/Chart.yaml, charts/vh-bookings-api/values.yaml
VIH-9004
Lint the helm during CI
Remove the release before releasing in PR release
```
[ ] Yes
[ x ] No
```
=> VIH-9004 - Lint helm and remove deployment during release

BookingsApi/BookingsApi.AcceptanceTests/packages.lock.json, BookingsApi/BookingsApi.Contract/BookingsApi.Contract.csproj, BookingsApi/BookingsApi.Contract/Requests/ParticipantRequest.cs, BookingsApi/BookingsApi.DAL/packages.lock.json, BookingsApi/BookingsApi.IntegrationTests/packages.lock.json, BookingsApi/BookingsApi.UnitTests/packages.lock.json, BookingsApi/BookingsApi/packages.lock.json
###JIRA link (if applicable)###
https://tools.hmcts.net/jira/browse/VIH-8867
 https://tools.hmcts.net/jira/browse/VIH-8878
###Change description###
Added contract validation attributes to DisplayName on the ParicipantRequest model
```
[ x] Yes
[ ] No
```
=> VIH-8867 VIH-8878 Add character limit and regex validation to participant display name on endpoints

BookingsApi/BookingsApi.DAL/Queries/GetHearingsForNotificationsQuery.cs, BookingsApi/BookingsApi.IntegrationTests/Database/Queries/GetHearingsForNotificationsQueryHandlerTests.cs
[VIH-9050](https://tools.hmcts.net/jira/browse/VIH-9050)
- updated query to include unconfirmed hearings
```
[ ] Yes
[x] No
```
=> VIH-9050 updated query to include unconfirmed hearings

BookingsApi/BookingsApi.Domain/JudiciaryPerson.cs, BookingsApi/BookingsApi.UnitTests/Domain/JudiciaryPersons/UpdateJudiciaryPersonTests.cs
VIH-9079
- setting personal data to null for accounts with leave flag set to true
```
[ ] Yes
[x] No
```
=> VIH-9079 wipe out leavers data

BookingsApi/BookingsApi.AcceptanceTests/packages.lock.json, BookingsApi/BookingsApi.IntegrationTests/packages.lock.json, BookingsApi/BookingsApi.UnitTests/packages.lock.json, BookingsApi/BookingsApi/BookingsApi.csproj, BookingsApi/BookingsApi/Program.cs, BookingsApi/BookingsApi/packages.lock.json
https://tools.hmcts.net/jira/browse/VIH-9099
Removed references to Vh.Core.Configuration
```
[ ] Yes
[x] No
```
=> VIH-9099 Removed references to Vh.Core.Configuration

BookingsApi/BookingsApi.UnitTests/Controllers/JudiciaryPersonControllerTests.cs, BookingsApi/BookingsApi/Controllers/JudiciaryPersonController.cs
https://tools.hmcts.net/jira/browse/VIH-9111
Only send the update judiciary person command to the database if there is something to update (the HasLeft flag).
```
[ ] Yes
[x] No
```
=> VIH-9111 Only update judiciary person if HasLeft has changed

azure-pipelines.sds.pr-close.yml, azure-pipelines.sds.pr-release.yml, azure-pipelines.sds.release.yml, sds-git-version-config.yml, variables/shared.yaml
VIH-9084
Add nuget pattern to SDS Pipeline as per https://tools.hmcts.net/confluence/display/VIH/Artifacts+Pipeline
```
[ ] Yes
[ x ] No
```
=> VIH-9084 Add nuget pattern to SDS Pipeline

charts/vh-bookings-api/values.dev.template.yaml
N/A
Update Dev template.
```
[ ] Yes
[X ] No
```
=> VIH-9999 - Update Dev Resource ID Helm

BookingsApi/BookingsApi/Dockerfile, BookingsApi/nuget.sds.config, azure-pipelines.sds.pr-release.yml, variables/staging.yaml
update issue found through E2E Testing.
- update Display Names.
- correct NuGet Feed in SDS.
```
[ ] Yes
[ X ] No
```
=> VIH-9999 - End To End Testing

azure-pipelines.sds.release.yml
add NuGet Config to SDS Release
```
[ ] Yes
[ X ] No
```
=> VIH-9999 - add NuGet Config to SDS Release

variables/production.yaml, variables/staging.yaml
Correct image tag for SDS
```
[ ] Yes
[ x ] No
```
=> VIH-8971 - Correct image tag for SDS

azure-pipelines.sds.pr-release.yml
VIH-8965
Change Bump Source Branch
```
[ ] Yes
[ x ] No
```
=> VIH-8965 - change bump version source

BookingsApi/BookingsApi.Common/Services/FeatureToggles.cs
https://tools.hmcts.net/jira/browse/VIH-9167
Changed launchDarkly logging level to Warn and above to reduce verbosity in pipeline logs
```
[ ] Yes
[X] No
```
=> VIH-9167 configure logging level for LaunchDarkly 

BookingsApi/BookingsApi.DAL/Services/HearingService.cs
=> VIH-8884 person search based on both the username or contact email.

BookingsApi/BookingsApi.AcceptanceTests/Steps/HearingsSteps.cs, BookingsApi/BookingsApi.Client/BookingsApiClient.cs, BookingsApi/BookingsApi.Common/Services/FeatureToggles.cs, BookingsApi/BookingsApi.Contract/Requests/BookNewHearingRequest.cs, BookingsApi/BookingsApi.Contract/Responses/CaseTypeResponse.cs, BookingsApi/BookingsApi.DAL/BookingsApi.DAL.csproj, BookingsApi/BookingsApi.DAL/Migrations/20220714095834_AddedCaseTypePropertiesLiveAndServiceId.Designer.cs, BookingsApi/BookingsApi.DAL/Migrations/20220714095834_AddedCaseTypePropertiesLiveAndServiceId.cs, BookingsApi/BookingsApi.DAL/Queries/GetCaseRolesForCaseTypeQuery.cs, BookingsApi/BookingsApi.Domain/RefData/CaseType.cs, BookingsApi/BookingsApi.IntegrationTests/Database/Queries/GetCaseTypeQueryHandlerDatabaseTests.cs, BookingsApi/BookingsApi.UnitTests/Controllers/CaseTypes/CaseTypesControllerTests.cs, BookingsApi/BookingsApi.UnitTests/Controllers/CaseTypes/GetCaseTypesTests.cs, BookingsApi/BookingsApi.UnitTests/Controllers/HearingsController/BookNewHearingTests.cs, BookingsApi/BookingsApi.UnitTests/Controllers/HearingsController/HearingsControllerTests.cs, BookingsApi/BookingsApi.UnitTests/Controllers/HearingsController/Helpers/RequestBuilder.cs, BookingsApi/BookingsApi/Controllers/CaseTypesController.cs, BookingsApi/BookingsApi/Controllers/HearingsController.cs
https://tools.hmcts.net/jira/browse/VIH-9064
Potentially a breaking change as ive updated request/response contracts, and the naming of a parameter
```
[X] Yes
[ ] No
```
=> VIH-9064 add attributes to casetype and validation logic

charts/vh-bookings-api/Chart.yaml, charts/vh-bookings-api/values.yaml
https://tools.hmcts.net/jira/browse/VIH-9019
Add values from ADO library to values.yaml
```
[ ] Yes
[ X] No
```
=> VIH-9019 Add values from library to chart values

azure-pipelines.sds.pr-release.yml, azure-pipelines.sds.release.yml, sds-git-version-config.yml, variables/test.yaml
VIH-9193
Add Test Environment
```
[ ] Yes
[ x ] No
```
=> VIH-9193 - Add Test Environment

BookingsApi/BookingsApi.DAL/Queries/GetPersonBySearchTermQuery.cs, BookingsApi/BookingsApi.IntegrationTests/Database/Queries/GetPersonBySearchTermQueryHandlerDatabaseTests.cs, BookingsApi/BookingsApi.IntegrationTests/Database/Queries/GetPersonBySearchTermQueryHandlerEFCoreTests.cs
https://tools.hmcts.net/jira/browse/VIH-9186
Change person search to a fuzzy match (search by Contains instead of StartsWith)
```
[ ] Yes
[x] No
```
=> VIH-9186 Change participant search to fuzzy match

charts/vh-bookings-api/Chart.yaml, charts/vh-bookings-api/values.yaml
VIH-9329
VIH-9329 - update app settings
```
[ ] Yes
[ x ] No
```
=> VIH-9329 - update app settings

charts/vh-bookings-api/Chart.yaml, charts/vh-bookings-api/values.demo.template.yaml, charts/vh-bookings-api/values.dev.template.yaml, charts/vh-bookings-api/values.yaml
VIH-9236
Remove ENV overrides
```
[ ] Yes
[ x ] No
```
=> VIH-9236 - Remove ENV overrides

BookingsApi/BookingsApi.UnitTests/Controllers/HearingParticipantsController/AddParticipantsToHearingTests.cs, BookingsApi/BookingsApi.UnitTests/Validation/ParticipantRequestValidationTests.cs, BookingsApi/BookingsApi/Validations/ParticipantRequestValidation.cs
https://tools.hmcts.net/jira/browse/VIH-9211
Telephone number is currently required for a participant when saving a booking in the frontend but not in the backend. Add this validation to the backend
```
[ ] Yes
[x] No
```
=> VIH-9211 Booking Api Contact number is mandatory for all parties 

charts/vh-bookings-api/Chart.yaml, charts/vh-bookings-api/values.yaml
VIH-9236
Add Service Bus Config
```
[ ] Yes
[ x ] No
```
=> VIH-9236 - Add Service Bus Config

BookingsApi/BookingsApi.DAL/BookingsApi.DAL.csproj, BookingsApi/BookingsApi.DAL/BookingsDbContext.cs, BookingsApi/BookingsApi.DAL/Mappings/AllocationMap.cs, BookingsApi/BookingsApi.DAL/Mappings/DayOfWeekMap.cs, BookingsApi/BookingsApi.DAL/Mappings/JusticeUserMap.cs, BookingsApi/BookingsApi.DAL/Mappings/VhoNonAvailabilityMap.cs, BookingsApi/BookingsApi.DAL/Mappings/VhoWorkHoursMap.cs, BookingsApi/BookingsApi.DAL/Migrations/20220407104039_AddSENDCaseType.cs, BookingsApi/BookingsApi.DAL/Migrations/20220518082658_AddHearingTypeSubstantiveHearing.cs, BookingsApi/BookingsApi.DAL/Migrations/20220824154519_AddVhoWorkAllocationTables.Designer.cs, BookingsApi/BookingsApi.DAL/Migrations/20220824154519_AddVhoWorkAllocationTables.cs, BookingsApi/BookingsApi.Domain/Allocation.cs, BookingsApi/BookingsApi.Domain/DayOfWeek.cs, BookingsApi/BookingsApi.Domain/JusticeUser.cs, BookingsApi/BookingsApi.Domain/VhoNonAvailability.cs, BookingsApi/BookingsApi.Domain/VhoWorkHours.cs
https://tools.hmcts.net/jira/browse/VIH-9231
This piece also identified issues with two previous migration scripts where the dates where entered using raw sql and were formatted incorrectly. They prevented integration tests from running on new databases.
=> VIH-9231 Added VHO Allocation tables

BookingsApi/BookingsApi.Infrastructure.Services/IntegrationEvents/Events/JudgeUpdatedIntegrationEvent.cs, BookingsApi/BookingsApi.Infrastructure.Services/ParticipantDtoExtension.cs, BookingsApi/BookingsApi.Infrastructure.Services/ServiceBusQueue/ServiceBusQueueClientFake.cs, BookingsApi/BookingsApi.UnitTests/Controllers/HearingParticipantsController/UpdateHearingParticipantsTests.cs, BookingsApi/BookingsApi.UnitTests/Controllers/HearingsController/UpdateHearingDetailsTests.cs, BookingsApi/BookingsApi/Controllers/HearingParticipantsController.cs, BookingsApi/BookingsApi/Controllers/HearingsController.cs
https://tools.hmcts.net/jira/browse/VIH-9230
Reintroduced logic for checking the hearing otherInformation details have been updated (with a new judge email) and created an event to publish to the BookingSchedulerJobs to update the videoApi and send a notify email. Also includes a fix to send an update to the videoApi for any participant details that have been updated such as display name, as previously this event would be fired if a new participant is added.
```
[ ] Yes
[X] No
```
=> VIH-9230 JudgeUpdatedIntegrationEvent added and condition logic to fire event

BookingsApi/BookingsApi.AcceptanceTests/Models/AddParticipantRequest.cs, BookingsApi/BookingsApi.AcceptanceTests/Steps/ParticipantsSteps.cs, BookingsApi/BookingsApi.DAL/Commands/UpdateJudiciaryPersonByExternalRefIdCommand.cs, BookingsApi/BookingsApi.UnitTests/Controllers/HearingParticipantsController/AddParticipantsToHearingTests.cs, BookingsApi/BookingsApi.UnitTests/Validation/ParticipantRequestValidationTests.cs, BookingsApi/BookingsApi/Validations/ParticipantRequestValidation.cs
https://tools.hmcts.net/jira/browse/VIH-9280
Recreation of pr/497
```
[ ] Yes
[X] No
```
=> VIH-9280 added regular expression to first last name

BookingsApi/BookingsApi.Client/BookingsApiClient.cs, BookingsApi/BookingsApi.Contract/Responses/JusticeUserResponse.cs, BookingsApi/BookingsApi.DAL/Queries/GetJusticeUserByUsernameQuery.cs, BookingsApi/BookingsApi.Domain/RefData/UserRole.cs, BookingsApi/BookingsApi.IntegrationTests/Constants/UserRoleId.cs, BookingsApi/BookingsApi.IntegrationTests/Database/DatabaseTestsBase.cs, BookingsApi/BookingsApi.IntegrationTests/Database/Queries/GetJusticeUsersByUsernameQueryHandlerDatabaseTests.cs, BookingsApi/BookingsApi.IntegrationTests/Helper/TestDataManager.cs, BookingsApi/BookingsApi.UnitTests/Constants/UserRoleId.cs, BookingsApi/BookingsApi.UnitTests/Controllers/JusticeUserControllerTests.cs, BookingsApi/BookingsApi.UnitTests/Mappings/JusticeUserToResponseMapperTests.cs, BookingsApi/BookingsApi/Controllers/JusticeUserController.cs, BookingsApi/BookingsApi/Mappings/JusticeUserToResponseMapper.cs
https://tools.hmcts.net/jira/browse/VIH-9291
=> VIH-9291 Added endpoint to return justice user via username

BookingsApi/BookingsApi.Client/BookingsApiClient.cs, BookingsApi/BookingsApi.Contract/Requests/DayWorkHours.cs, BookingsApi/BookingsApi.Contract/Requests/UploadWorkAllocationRequest.cs, BookingsApi/BookingsApi.Contract/Requests/WorkHours.cs, BookingsApi/BookingsApi.Contract/Requests/WorkingHours.cs, BookingsApi/BookingsApi.DAL/Commands/UploadWorkHoursCommand.cs, BookingsApi/BookingsApi.DAL/Migrations/20221003094745_AddDaysOfTheWeek.Designer.cs, BookingsApi/BookingsApi.DAL/Migrations/20221003094745_AddDaysOfTheWeek.cs, BookingsApi/BookingsApi.DAL/Migrations/20221003151746_AllowNullableWorkHours.Designer.cs, BookingsApi/BookingsApi.DAL/Migrations/20221003151746_AllowNullableWorkHours.cs, BookingsApi/BookingsApi.Domain/VhoWorkHours.cs, BookingsApi/BookingsApi.IntegrationTests/Database/Commands/UploadWorkHoursCommandTests.cs, BookingsApi/BookingsApi.UnitTests/Controllers/WorkAllocationControllerTests.cs, BookingsApi/BookingsApi.UnitTests/Validation/UploadWorkAllocationRequestsValidationTests.cs, BookingsApi/BookingsApi/Controllers/WorkAllocationController.cs, BookingsApi/BookingsApi/Validations/UploadWorkAllocationRequestsValidation.cs
https://tools.hmcts.net/jira/browse/VIH-9315
=> VIH-9315 Save Justice User working hours

azure-pipelines.sds.release.yml
Remove Version Error
```
[ ] Yes
[ x ] No
```
=> VIH-9999 - Remove Version Error

BookingsApi/BookingsApi.Client/BookingsApiClient.cs, BookingsApi/BookingsApi.Contract/Responses/VhoSearchResponse.cs, BookingsApi/BookingsApi.Contract/Responses/VhoWorkHoursResponse.cs, BookingsApi/BookingsApi.DAL/Queries/GetVhoWorkHoursQuery.cs, BookingsApi/BookingsApi.IntegrationTests/Database/Queries/GetVhoWorkHoursQueryHandlerDatabaseTests.cs, BookingsApi/BookingsApi.UnitTests/Controllers/WorkAllocationControllerTests.cs, BookingsApi/BookingsApi.UnitTests/Controllers/WorkHoursControllerTests.cs, BookingsApi/BookingsApi/Controllers/WorkHoursController.cs, BookingsApi/BookingsApi/Mappings/VhoWorkHoursToResponseMapper.cs
=> VIH-9277 GetVhoWorkHours controller and DAL query

BookingsApi/BookingsApi.DAL/Migrations/test.txt, azure-pipelines.sds.pr-release.yml
VIH-9241
Check if EF changes before running
```
[ ] Yes
[ x ] No
```
=> VIH-9241 - Add template checks

azure-pipelines.sds.release.yml
=> VIH-9999 - Update Migrations Path

BookingsApi/BookingsApi.DAL/Commands/UpdateHearingCommand.cs, BookingsApi/BookingsApi.DAL/Commands/UpdateHearingStatusCommand.cs, BookingsApi/BookingsApi.DAL/Commands/UpdateNonWorkingHoursCommand.cs, BookingsApi/BookingsApi.DAL/Commands/UploadNonWorkingHoursCommand.cs, BookingsApi/BookingsApi.DAL/Commands/UploadWorkHoursCommand.cs, BookingsApi/BookingsApi.DAL/Queries/GetHearingByIdQuery.cs, BookingsApi/BookingsApi.DAL/Services/HearingAllocationService.cs, BookingsApi/BookingsApi.Domain/Hearing.cs, BookingsApi/BookingsApi.Domain/JusticeUser.cs, BookingsApi/BookingsApi.IntegrationTests/Database/AllocationDatabaseTestsBase.cs, BookingsApi/BookingsApi.IntegrationTests/Database/Commands/UpdateHearingCommandTests.cs, BookingsApi/BookingsApi.IntegrationTests/Database/Commands/UpdateHearingStatusCommandTests.cs, BookingsApi/BookingsApi.IntegrationTests/Database/Commands/UpdateNonWorkingHoursCommandTests.cs, BookingsApi/BookingsApi.IntegrationTests/Database/Commands/UploadNonWorkingHoursCommandTests.cs, BookingsApi/BookingsApi.IntegrationTests/Database/Commands/UploadWorkHoursCommandTests.cs, BookingsApi/BookingsApi.UnitTests/DAL/Services/HearingAllocationServiceTests.cs, BookingsApi/BookingsApi.UnitTests/Domain/Hearing/UpdateHearingDetailsTests.cs
https://tools.hmcts.net/jira/browse/VIH-9394
Automatically deallocate a hearing when
- Cancelling the hearing
- Changing the hearing's scheduled datetime
- Updating the work hours such that the user is no longer available for the hearing
- Updating the non availabilities such that the user is no longer available for the hearing
```
[ ] Yes
[x] No
```
=> VIH-9394 Automatically deallocate hearings

azure-pipelines.release.yml, azure-pipelines.sds.master-release.yml, azure-pipelines.sds.pr-close.yml, azure-pipelines.sds.pr-release.yml, azure-pipelines.sds.release.yml
https://tools.hmcts.net/jira/browse/VIH-9544
Updated SDS pipelines with vmimage ubuntu 22.04, some pipelines stated that they had to be run on windows. 
```
[ ] Yes
[ X] No
```
=> VIH-9544 update vm image in pipeline

BookingsApi/BookingsApi.UnitTests/Controllers/HearingsController/CloneHearingTests.cs, BookingsApi/BookingsApi.UnitTests/Controllers/WorkHoursControllerTests.cs, BookingsApi/BookingsApi/Controllers/WorkHoursController.cs, BookingsApi/BookingsApi/Validations/CloneHearingRequestValidation.cs
https://tools.hmcts.net/jira/browse/VIH-9431
bug fix for overlap different years - update no working hours for user do not have any
=> VIH-9431 - edits Non-Availability hours for user that has not yet had any uploaded

BookingsApi/BookingsApi.UnitTests/Validation/UploadWorkHoursRequestsValidationTests.cs, BookingsApi/BookingsApi/Validations/UploadWorkHoursRequestsValidation.cs
https://tools.hmcts.net/jira/browse/VIH-9540
```
[ ] Yes
[X] No
```
=> VIH-9540 Added validation for duplicate users in work upload csv

BookingsApi/BookingsApi.Infrastructure.Services/ParticipantDtoExtension.cs, BookingsApi/BookingsApi.UnitTests/Infrastructure.Services/IntegrationEventTests.cs
…s used to extract email and phone values
- [x ] commit messages are meaningful and follow good commit message guidelines
- [ x] tests have been updated / new tests has been added (if needed)
```
[ ] Yes
[ x] No
```
=> VIH-9606 Empty or Null check on other information field

BookingsApi/BookingsApi.AcceptanceTests/Features/Hearings.feature, BookingsApi/BookingsApi.Domain/BookingStatusTransition.cs, BookingsApi/BookingsApi.IntegrationTests/Database/Commands/UpdateHearingStatusCommandTests.cs, BookingsApi/BookingsApi.IntegrationTests/Features/Hearings.feature, BookingsApi/BookingsApi.UnitTests/Controllers/Persons/UpdatePersonDetailsTests.cs
**Change description**
Removed one of the transition states as it is no longer valid. Status cannot be changed to failed from created status.
```
[ ] Yes
[x ] No
```
=> VIH-9607 Change to the bookings status transitions

BookingsApi/BookingsApi.DAL/Commands/UpdatePersonCommand.cs, BookingsApi/BookingsApi.DAL/Services/HearingService.cs, BookingsApi/BookingsApi.Domain/Participants/Participant.cs, BookingsApi/BookingsApi.Domain/Person.cs, BookingsApi/BookingsApi.UnitTests/Controllers/Persons/UpdatePersonDetailsTests.cs, BookingsApi/BookingsApi.UnitTests/Domain/Persons/UpdatePersonTests.cs
Removed contact email and username from the update method on the Person object as there is no need to update these details for an existing person.
```
[ ] Yes
[x ] No
```
=> VIH-9633 Update Person Changes

azure-pipelines.sds.master-release.yml, azure-pipelines.sds.release.yml
https://tools.hmcts.net/jira/browse/VIH-9650?filter=-1
Remove Test Environment from SDS application repo
```
[ ] Yes
[X ] No
```
=> VIH-9650 Removing Test environment

azure-pipelines.sds.release.yml
https://tools.hmcts.net/jira/browse/VIH-9642
HMCTS have asked for the Demo environment for VH to be recreated.
This environment is to be used strictly for Demos and will have a copy of Production releases.
1. Create Demo Infra via Terraform (Core & Wowza) 
2. Amend DNS 
3. Configure AFD
4. Add Flux Configuration 
5. Amend Release Pipelines to Run EF in Demo
```
[ ] Yes
[X ] No
```
=> VIH-9642 Create Demo environment in SDS

BookingsApi/BookingsApi.Client/BookingsApiClient.cs, BookingsApi/BookingsApi.UnitTests/Middleware/ExceptionMiddlewareTests.cs, BookingsApi/BookingsApi/BookingsApi.csproj, BookingsApi/BookingsApi/Controllers/EndPointsController.cs, BookingsApi/BookingsApi/Controllers/FeatureFlagsController.cs, BookingsApi/BookingsApi/Controllers/HearingParticipantsController.cs, BookingsApi/BookingsApi/Controllers/HearingsController.cs, BookingsApi/BookingsApi/Controllers/ParticipantsController.cs, BookingsApi/BookingsApi/Controllers/PersonsController.cs, BookingsApi/BookingsApi/Controllers/StaffMemberController.cs, BookingsApi/BookingsApi/Controllers/SuitabilityAnswersController.cs, BookingsApi/BookingsApi/Extensions/ExceptionMiddleware.cs, BookingsApi/BookingsApi/Startup.cs
VIH-9679
Apply 500 filter across all endpoints by default that they return a string (as defined by the ExceptionMiddleware.cs)
```
[ ] Yes
[x] No
```
=> VIH-9679 Add better exception handling

BookingsApi/BookingsApi.Client/BookingsApiClient.cs, BookingsApi/BookingsApi.DAL/Queries/GetJusticeUserListQuery.cs, BookingsApi/BookingsApi.IntegrationTests/Database/Queries/GetJusticeUsersListQueryHandlerDatabaseTests.cs, BookingsApi/BookingsApi.UnitTests/Controllers/JusticeUserControllerTests.cs, BookingsApi/BookingsApi/Controllers/JusticeUserController.cs
https://tools.hmcts.net/jira/browse/VIH-9353
added search term to api
=> VIH-9353 - added term filter to get user list

BookingsApi/BookingsApi.UnitTests/Domain/JusticeUser/IsDateBetweenWorkingHoursTests.cs, BookingsApi/BookingsApi.UnitTests/Domain/JusticeUser/IsDuringNonAvailableHoursTests.cs
VIH-9613 
Add missing unit tests
```
[ ] Yes
[x] No
```
=> VIH-9613 Add missing unit tests

BookingsApi/BookingsApi.Client/BookingsApiClient.cs, BookingsApi/BookingsApi.IntegrationTests/Api/JusticeUsers/AddJusticeUserTests.cs, BookingsApi/BookingsApi/Controllers/JusticeUserController.cs
VIH-9306
Update swagger documentation for AddJusticeUser endpoint
```
[ ] Yes
[x] No
```
=> VIH-9306 Update swagger documentation for AddJusticeUser endpoint

BookingsApi/BookingsApi.Contract/Responses/HearingAllocationsResponse.cs, BookingsApi/BookingsApi.DAL/Dtos/HearingAllocationResultDto.cs, BookingsApi/BookingsApi.DAL/Services/HearingAllocationService.cs, BookingsApi/BookingsApi.IntegrationTests/Services/HearingAllocationService/CheckForAllocationClashesTests.cs, BookingsApi/BookingsApi/Mappings/HearingAllocationResultDtoToAllocationResponseMapper.cs
VIH-9630
- calculate number of concurrent hearings
- return true if exceeds 3
```
[x] Yes
[] No
```
=> VIH-9630 calculate concurrent hearing count

BookingsApi/BookingsApi.Contract/Responses/HearingAllocationsResponse.cs, BookingsApi/BookingsApi.DAL/Dtos/HearingAllocationResultDto.cs, BookingsApi/BookingsApi.DAL/Services/HearingAllocationService.cs, BookingsApi/BookingsApi.IntegrationTests/Services/HearingAllocationService/CheckForAllocationClashesTests.cs, BookingsApi/BookingsApi.UnitTests/Controllers/WorkAllocationsController/SearchForAllocationHearingsTests.cs, BookingsApi/BookingsApi/Mappings/HearingAllocationResultDtoToAllocationResponseMapper.cs, BookingsApi/BookingsApi/Startup.cs
https://tools.hmcts.net/jira/browse/VIH-9631
```
[ ] Yes
[x ] No
```
=> VIH-9631 check for nonavailability clash

azure-pipelines.sds.release.yml
VIH-9999 - Update Variable Group Error
```
[ ] Yes
[ x ] No
```
=> VIH-9999 - Update Variable Group Error

BookingsApi/BookingsApi.Client/BookingsApiClient.cs, BookingsApi/BookingsApi.Contract/Requests/EditJusticeUserRequest.cs, BookingsApi/BookingsApi.DAL/Commands/EditJusticeUserCommand.cs, BookingsApi/BookingsApi.IntegrationTests/Api/JusticeUsers/AddJusticeUserTests.cs, BookingsApi/BookingsApi.IntegrationTests/Api/JusticeUsers/EditJusticeUserTests.cs, BookingsApi/BookingsApi.IntegrationTests/Database/Commands/EditJusticeUserCommandTests.cs, BookingsApi/BookingsApi.UnitTests/Validation/EditJusticeUserRequestValidationTests.cs, BookingsApi/BookingsApi/Controllers/JusticeUserController.cs, BookingsApi/BookingsApi/Validations/EditJusticeUserRequestValidation.cs, BookingsApi/Testing.Common/Builders/Api/ApiUriFactory.cs
VIH-9352
* add edit user endpoint, request type & command
```
[ ] Yes
[x] No
```
=> VIH-9352 add edit user endpoint

BookingsApi/BookingsApi.DAL/Mappings/JusticeUserMap.cs, BookingsApi/BookingsApi.DAL/Migrations/20230306161937_AddUniqueConstrainForJusticeUserColumn.Designer.cs, BookingsApi/BookingsApi.DAL/Migrations/20230306161937_AddUniqueConstrainForJusticeUserColumn.cs, BookingsApi/BookingsApi.IntegrationTests/Database/Queries/GetVhoWorkHoursQueryHandlerDatabaseTests.cs
https://tools.hmcts.net/jira/browse/VIH-9746
Added the Column Constrain , fixed the unit tests were breaking .
```
[ ] Yes
[ x] No
```
=> VIH-9476 added unique constrain to justice user table 

BookingsApi/BookingsApi.UnitTests/Validation/AddJusticeUserRequestValidationTests.cs
VIH-9306
house keeping
```
[ ] Yes
[x] No
```
=> VIH-9306 clean up test data

BookingsApi/BookingsApi/Validations/ParticipantRequestValidation.cs
https://tools.hmcts.net/jira/browse/VIH-9788
Removed phone validation from add participant request (kept it on addnjusticeUser request). As invalid numbers/non UK numbers are expected and allowed.
```
[ ] Yes
[X] No
```
=> VIH-9788 Removed participantRequest phone validation

azure-pipelines.sds.pr-release.yml
add PR param to allow a manual trigger
```
[ ] Yes
[x] No
```
=> VIH-0000 add pr param

BookingsApi/BookingsApi.AcceptanceTests/Models/SimpleBookNewHearingRequest.cs, BookingsApi/BookingsApi.UnitTests/Controllers/WorkAllocationsController/AllocateHearingManuallyTests.cs, BookingsApi/BookingsApi.UnitTests/Controllers/WorkAllocationsController/WorkAllocationsControllerTest.cs, BookingsApi/BookingsApi/Controllers/WorkAllocationsController.cs, BookingsApi/Testing.Common/Builders/Domain/VideoHearingBuilder.cs
VIH-9877
* publish only hearings today to the service bus for allocation notification
```
[ ] Yes
[x] No
```
=> VIH-9877 publish only hearings today to the service bus for allocation notification

BookingsApi/BookingsApi.Client/BookingsApiClient.cs, BookingsApi/BookingsApi/Controllers/HearingParticipantsController.cs
1. Updated endpoints:
- POST Add participant
- PUT Edit participant
2. Regenerated client
Test pr https://vh-admin-web-pr-1205.dev.platform.hmcts.net/home
=> VIH-0000 Added response type attributes for swagger documentation

BookingsApi/BookingsApi/Startup.cs
TBC
* enable retry on failed sql connections, Video and Notification API already do this, Bookings API was outstanding
```
[ ] Yes
[x] No
```
=> VIH-0000 Enable retry on failed sql connections

BookingsApi/BookingsApi.Contract/Helper/HearingScottishVenueNames.cs, RefData/data/9777_rename_venues_and_add_venue_codes.sql
VIH-9777
Add sql script to rename venues and add venue codes
```
[ ] Yes
[x] No
```
=> VIH-9777 Add sql script to rename venues and add venue codes

RefData/data/9965_add_private_law_case_type.sql, RefData/data/9987_add_venue_codes.sql
VIH-9965
data fixes for venue codes and private law case type scripts
```
[ ] Yes
[x] No
```
=> VIH-9965 data fixes for ref data scripts

azure-pipelines.sds.pr-release.yml, azure-pipelines.sds.release.yml, azure-pipelines.yml, charts/vh-bookings-api/Chart.yaml, charts/vh-bookings-api/values.dev.template.yaml
https://tools.hmcts.net/jira/browse/VIH-9972
- Replace instrumentation key with connection string
```
[ ] Yes
[x] No
```
=> VIH-9972 Update app insights config

BookingsApi/BookingsApi.DAL/Queries/GetCaseRolesForCaseTypeQuery.cs, BookingsApi/BookingsApi.IntegrationTests/Api/Hearings/BookNewHearingWithRefDataToggleOnTests.cs, BookingsApi/BookingsApi.IntegrationTests/Database/Queries/GetCaseTypeQueryHandlerDatabaseTests.cs, BookingsApi/BookingsApi/Controllers/HearingsController.cs
VIH-10066
Ignore case sensitivity for service ids, venue codes and hearing type codes
```
[ ] Yes
[x] No
```
=> VIH-10066 Ignore case sensitivity ref data codes

BookingsApi/BookingsApi.DAL/Mappings/HearingVenueMap.cs, BookingsApi/BookingsApi.DAL/Mappings/RefData/HearingTypeMap.cs, BookingsApi/BookingsApi.DAL/Migrations/20230811111745_AddUniqueMappingsForCodes.Designer.cs, BookingsApi/BookingsApi.DAL/Migrations/20230811111745_AddUniqueMappingsForCodes.cs, RefData/data/9987_add_venue_codes.sql
https://tools.hmcts.net/jira/browse/VIH-10046
- Adds unique constraints to Hearing Type code and Hearing Venue code
- Updates a ref data script to use unique hearing venue ids instead of 9999
```
[ ] Yes
[x] No
```
=> VIH-10046 Add unique constraints on code properties

BookingsApi/BookingsApi.UnitTests/Validation/V1/EmailValidatorTests.cs, BookingsApi/BookingsApi.UnitTests/Validation/V1/ParticipantRequestValidationTests.cs, BookingsApi/BookingsApi/Validations/EmailValidator.cs
VIH-10105
Update regex to fail email validation when an ampersand is present
```
[ ] Yes
[x] No
```
=> VIH-10105 Update valid email regex

BookingsApi/BookingsApi.Client/BookingsApiClient.cs, BookingsApi/BookingsApi.DAL/Commands/RemoveHearingCommand.cs, BookingsApi/BookingsApi.DAL/Commands/RemoveJudiciaryParticipantFromHearingCommand.cs, BookingsApi/BookingsApi.Domain/Hearing.cs, BookingsApi/BookingsApi.Domain/Validations/DomainRuleErrorMessages.cs, BookingsApi/BookingsApi.IntegrationTests/Api/V1/JudiciaryParticipants/RemoveJudiciaryParticipantFromHearingTests.cs, BookingsApi/BookingsApi.IntegrationTests/Database/Commands/RemoveJudiciaryParticipantFromHearingCommandTests.cs, BookingsApi/BookingsApi.IntegrationTests/Helper/SeedVideoHearingOptions.cs, BookingsApi/BookingsApi.IntegrationTests/Helper/TestDataManager.cs, BookingsApi/BookingsApi.UnitTests/Domain/Hearing/RemoveJudiciaryParticipantByPersonalCodeTests.cs, BookingsApi/BookingsApi.UnitTests/Domain/Hearing/RemoveJudiciaryParticipantTests.cs, BookingsApi/BookingsApi/Controllers/V1/JudiciaryParticipantsController.cs, BookingsApi/Testing.Common/Builders/Api/ApiUriFactory.cs, BookingsApi/Testing.Common/Builders/Domain/VideoHearingBuilder.cs
VIH-10091
remove judiciary office holder from hearing
```
[ ] Yes
[x] No
```
=> VIH-10091 remove judiciary office holder from hearing

BookingsApi/BookingsApi.Contract/V2/Requests/BookNewHearingRequestV2.cs, BookingsApi/BookingsApi.DAL/BookingsApi.DAL.csproj, BookingsApi/BookingsApi.DAL/Commands/AddJudiciaryParticipantsToHearingCommand.cs, BookingsApi/BookingsApi.DAL/Commands/CreateVideoHearingCommand.cs, BookingsApi/BookingsApi.DAL/Dtos/NewJudiciaryParticipant.cs, BookingsApi/BookingsApi.DAL/Services/HearingService.cs, BookingsApi/BookingsApi.Domain/Hearing.cs, BookingsApi/BookingsApi.Domain/Participants/Participant.cs, BookingsApi/BookingsApi.Domain/Validations/DomainRuleErrorMessages.cs, BookingsApi/BookingsApi.IntegrationTests/Api/V2/Hearings/BookNewHearingV2Tests.cs, BookingsApi/BookingsApi.IntegrationTests/Database/Commands/AddJudiciaryParticipantsToHearingCommandTests.cs, BookingsApi/BookingsApi.IntegrationTests/Helper/TestDataManager.cs, BookingsApi/BookingsApi.UnitTests/Domain/AnonymisationData/GetAnonymisationDataQueryHandlerTests.cs, BookingsApi/BookingsApi.UnitTests/Domain/Participants/AnonymiseCaseAndParticipantCommandTests.cs, BookingsApi/BookingsApi/Controllers/V2/HearingsControllerV2.cs, BookingsApi/BookingsApi/Mappings/V2/BookNewHearingRequestV2ToCreateVideoHearingCommandMapper.cs, BookingsApi/BookingsApi/Validations/V2/BookNewHearingRequestInputValidationV2.cs
VIH-10089
Update `BookHearingV2` endpoint to support judiciary participants
```
[ ] Yes
[x] No
```
=> VIH-10089 Update BookHearing V2 to support Judiciary Participants

BookingsApi/BookingsApi.Domain/Hearing.cs, BookingsApi/BookingsApi.Domain/RefData/HearingRole.cs, BookingsApi/BookingsApi.Domain/Validations/DomainRuleErrorMessages.cs, BookingsApi/BookingsApi.IntegrationTests/Api/V1/HearingParticipants/RemoveParticipantFromHearingTests.cs, BookingsApi/BookingsApi.IntegrationTests/Api/V2/HearingParticipants/AddParticipantsToHearingV2Tests.cs, BookingsApi/BookingsApi.UnitTests/Domain/Hearing/CanHearingBeUpdatedTests.cs, BookingsApi/BookingsApi/Controllers/V2/HearingParticipantsControllerV2.cs, BookingsApi/BookingsApi/Extensions/ExceptionMiddleware.cs
VIH-10161
Add domain rules for editing a Hearing
```
[ ] Yes
[x] No
```
=> VIH-10161 Add domain rules for editing a Hearing

BookingsApi/BookingsApi.Domain/Hearing.cs, BookingsApi/BookingsApi.Domain/Validations/DomainRuleErrorMessages.cs, BookingsApi/BookingsApi.IntegrationTests/Api/V1/HearingParticipants/RemoveParticipantFromHearingTests.cs, BookingsApi/BookingsApi.IntegrationTests/Api/V1/Hearings/UpdateHearingTests.cs, BookingsApi/BookingsApi.IntegrationTests/Api/V1/JudiciaryParticipants/UpdateJudiciaryParticipantTests.cs, BookingsApi/BookingsApi.IntegrationTests/Api/V2/Hearings/UpdateHearingV2Tests.cs, BookingsApi/BookingsApi.UnitTests/Domain/Hearing/CanHearingBeUpdatedTests.cs
VIH-10143
Improve validation failure verbosity to enable clear reasons for failure
=> VIH-10143 Improve validation failure verbosity

BookingsApi/BookingsApi.DAL/Queries/GetBookingsByCaseTypesQuery.cs, BookingsApi/BookingsApi.IntegrationTests/Database/Queries/GetBookingsByCaseTypesQueryHandlerTest.cs
https://tools.hmcts.net/jira/browse/VIH-10223
Reinstates the partial match case number search which was removed inadvertently in a previous change
=> VIH-10223 Partial match stopped working on search by case number in AdminWeb Booking list

azure-pipelines.sds.release.yml
Fixes a displayName error when running the sds.release pipeline for staging
=> VIH-0000 Fix displayName error for pipeline

BookingsApi/BookingsApi.Contract/V2/Requests/BookNewHearingRequestV2.cs
VIH-10186
Update property name for json schema for V2 models
=> VIH-10186 update V2 contracts

BookingsApi/BookingsApi.DAL/Queries/GetHearingsByUsernameForDeletionQuery.cs, BookingsApi/BookingsApi.DAL/Services/HearingAllocationService.cs, BookingsApi/BookingsApi.Domain/Hearing.cs, BookingsApi/BookingsApi.IntegrationTests/Api/V1/WorkAllocation/AllocateHearingManuallyTests.cs, BookingsApi/BookingsApi.IntegrationTests/Database/Queries/GetHearingsByUsernameForDeletionQueryHandlerTests.cs, BookingsApi/BookingsApi.IntegrationTests/Steps/PersonsSteps.cs, BookingsApi/BookingsApi.IntegrationTests/Steps/SearchForPersonSteps.cs, BookingsApi/BookingsApi.UnitTests/Controllers/WorkAllocationsController/AllocateHearingManuallyTests.cs, BookingsApi/BookingsApi.UnitTests/Domain/Hearing/UpdateStatusTest.cs, BookingsApi/BookingsApi.UnitTests/Mappings/V1/AudioRecordedHearingsBySearchResponseMapperTests.cs, BookingsApi/BookingsApi.UnitTests/Mappings/V1/HearingAllocationDtoMapperTests.cs, BookingsApi/BookingsApi.UnitTests/Mappings/V1/VideoHearingToBookingsResponseMapperTest.cs, BookingsApi/BookingsApi/Controllers/V1/PersonsController.cs, BookingsApi/BookingsApi/Controllers/V1/WorkAllocationsController.cs, BookingsApi/BookingsApi/Mappings/V1/AudioRecordedHearingsBySearchResponseMapper.cs, BookingsApi/Testing.Common/Builders/Api/ApiUriFactory.cs
VIH-10249
Include the list of participants and judiciary participants in db query.
Add API tests to protect from future changes
=> VIH-10249 judge display name null for allocation notification

BookingsApi/BookingsApi.UnitTests/Extensions/ContractExtensionTests.cs, BookingsApi/BookingsApi.UnitTests/Mappings/V1/VideoHearingToBookingsResponseMapperTest.cs, BookingsApi/BookingsApi/Extensions/ContractExtensions.cs, BookingsApi/BookingsApi/Mappings/V1/AudioRecordedHearingsBySearchResponseMapper.cs, BookingsApi/BookingsApi/Mappings/V1/HearingToDetailsResponseMapper.cs, BookingsApi/BookingsApi/Mappings/V1/VideoHearingToBookingsResponseMapper.cs, BookingsApi/BookingsApi/Mappings/V2/HearingToDetailsResponseV2Mapper.cs, BookingsApi/BookingsApi/Mappings/V2/ParticipantToResponseV2Mapper.cs
VIH-10263
all string properties should be cleaned before processing
=> VIH-10263 trim all strings recursively in booking

azure-pipelines.sds.master-release.yml
https://tools.hmcts.net/jira/browse/VIH-10259
remove param and add ef to test
=> VIH-10259 remove param and add ef to test

BookingsApi/BookingsApi.Infrastructure.Services/ParticipantDtoMapper.cs, BookingsApi/BookingsApi.UnitTests/Mappings/V1/IntegrationDtoMapperTests.cs
https://tools.hmcts.net/jira/browse/VIH-10176
Trim participant full name to account for participants without a title
=> VIH-10176 Trim the full name when sending from Bookings API to BQS

BookingsApi/BookingsApi.IntegrationTests/Api/V1/Hearings/BookNewHearingTests.cs, BookingsApi/BookingsApi.UnitTests/Validation/V1/ParticipantRequestValidationTests.cs, BookingsApi/BookingsApi/Validations/V1/ParticipantRequestValidation.cs, BookingsApi/Testing.Common/Builders/Api/V1/Request/SimpleBookNewHearingRequest.cs, BookingsApi/Testing.Common/Data/TestUsers.cs
Change the telephone number attribute to optional for panel members for the V1 endpoint. This change is to unblock some of the integration test scenarios that the S&L team is performing.
=> VIH-10309 Make telephone number optional for panel members

BookingsApi/BookingsApi.UnitTests/Validation/V1/ParticipantRequestValidationTests.cs, BookingsApi/BookingsApi/Validations/V1/ParticipantRequestValidation.cs
made case insensitive when comparing the roles in the validation
=> VIH-10309 made case insensitive when comparing the roles

BookingsApi/BookingsApi.DAL/Queries/GetAllocationHearingsBySearchQuery.cs, BookingsApi/BookingsApi.IntegrationTests/Database/Queries/GetAllocationHearingsBySearchQueryTests.cs, BookingsApi/BookingsApi.IntegrationTests/Helper/SeedVideoHearingOptions.cs, BookingsApi/BookingsApi.IntegrationTests/Helper/TestDataManager.cs, BookingsApi/BookingsApi/Controllers/V1/WorkAllocationsController.cs, tests/Dockerfile
https://tools.hmcts.net/jira/browse/VIH-10298
Added query parameter to filter hearings that run into the following day
=> VIH-10298 Added query parameter to filter hearings that run into the following day

BookingsApi/BookingsApi.Client/BookingsApiClient.cs, BookingsApi/BookingsApi.IntegrationTests/Api/V1/Hearings/CloneHearingTests.cs, BookingsApi/BookingsApi.IntegrationTests/Features/V1/CloneHearing.feature, BookingsApi/BookingsApi.UnitTests/Controllers/HearingsController/CloneHearingTests.cs, BookingsApi/BookingsApi/Controllers/V1/HearingsController.cs
Retuning the response from Clone Hearing endpoint
=> VIH-10331 Retuning the response from Clone Hearing endpoint

BookingsApi/BookingsApi.DAL/Queries/BaseQueries/VideoHearings.cs, BookingsApi/BookingsApi.DAL/Queries/GetConfirmedHearingsByUsernameForTodayQuery.cs, BookingsApi/BookingsApi.IntegrationTests/Database/Queries/GetConfirmedHearingsByUsernameForTodayQueryHandlerTests.cs
https://tools.hmcts.net/jira/browse/VIH-10327
Include judiciary participants when fetching hearings for the current user
=> VIH-10327 Fix for cant join hearings as judiciary participant

BookingsApi/BookingsApi.DAL/Commands/UpdateHearingStatusCommand.cs, BookingsApi/BookingsApi.Domain/BookingStatusTransition.cs, BookingsApi/BookingsApi.Domain/Hearing.cs, BookingsApi/BookingsApi.IntegrationTests/Api/V1/CancelBooking/CancelBookingTests.cs, BookingsApi/BookingsApi.IntegrationTests/Api/V1/Hearings/UpdateBookingStatusTests.cs, BookingsApi/BookingsApi.IntegrationTests/Database/Commands/UpdateHearingStatusCommandTests.cs, BookingsApi/BookingsApi/Controllers/V1/EndPointsController.cs, BookingsApi/BookingsApi/Controllers/V1/HearingParticipantsController.cs, BookingsApi/BookingsApi/Services/BookingService.cs
Changes to update the booking status to ConfirmedWithoutJudge when there is no Judge in the list
=> VIH-10357 Fixed ConfirmedWithoutJudge Status issues

BookingsApi/BookingsApi.Infrastructure.Services/EventDtoMappers.cs, BookingsApi/BookingsApi.Infrastructure.Services/ParticipantDtoExtension.cs, BookingsApi/BookingsApi.Infrastructure.Services/ParticipantDtoMapper.cs, BookingsApi/BookingsApi.Infrastructure.Services/Publishers/CreateAndNotifyUserPublisher.cs, BookingsApi/BookingsApi.Infrastructure.Services/Publishers/HearingConfirmationforExistingParticipantsPublisher.cs, BookingsApi/BookingsApi.Infrastructure.Services/Publishers/HearingConfirmationforNewParticipantsPublisher.cs, BookingsApi/BookingsApi.Infrastructure.Services/Publishers/HearingNotoficationEventPublisher.cs, BookingsApi/BookingsApi.Infrastructure.Services/Publishers/MultidayHearingConfirmationforExistingParticipantsPublisher.cs, BookingsApi/BookingsApi.Infrastructure.Services/Publishers/MultidayHearingConfirmationforNewParticipantsPublisher.cs, BookingsApi/BookingsApi.Infrastructure.Services/Publishers/MultidayHearingNotoficationEventPublisher.cs, BookingsApi/BookingsApi.Infrastructure.Services/Publishers/WelcomeEmailForNewParticipantsPublisher.cs, BookingsApi/BookingsApi.UnitTests/Infrastructure.Services/EventDtoMappersTests.cs, BookingsApi/BookingsApi/Services/BookingService.cs
https://tools.hmcts.net/jira/browse/VIH-10377
When an other judge email or telephone number is specified on the admin web form, use these for notifications instead of the ones associated with the person record.
=> VIH-10377 Notify emails not being sent to the judges other email

BookingsApi/BookingsApi.AcceptanceTests/BookingsApi.AcceptanceTests.csproj, BookingsApi/BookingsApi.AcceptanceTests/packages.lock.json, BookingsApi/BookingsApi.Domain/Participants/Judge.cs, BookingsApi/BookingsApi.IntegrationTests/Database/Commands/UpdateHearingParticipantsCommandHandlerTests.cs, BookingsApi/BookingsApi.UnitTests/BookingsApi.UnitTests.csproj, BookingsApi/BookingsApi.UnitTests/packages.lock.json
[VIH-10384](https://tools.hmcts.net/jira/browse/VIH-10384)
added display name to Judge model
=> VIH-10384 - INC5573953 Editing hearing on Prod - Notify not sent

BookingsApi/BookingsApi.Infrastructure.Services/AsynchronousProcesses/ParticipantAddedToHearingAsynchronousProcess.cs, BookingsApi/BookingsApi.Infrastructure.Services/EventDtoMappers.cs, BookingsApi/BookingsApi.Infrastructure.Services/Publishers/HearingNotoficationEventPublisher.cs, BookingsApi/BookingsApi.Infrastructure.Services/Publishers/PublisherHelper.cs, BookingsApi/BookingsApi.IntegrationTests/Api/V1/Hearings/BookNewHearingTests.cs, BookingsApi/BookingsApi.IntegrationTests/Helper/TestDataManager.cs, BookingsApi/BookingsApi.UnitTests/Controllers/HearingsController/CloneHearingTests.cs, BookingsApi/BookingsApi.UnitTests/Domain/Participants/PersonAlreadyExistTests.cs, BookingsApi/BookingsApi.UnitTests/Services/BookingServiceTests.cs, BookingsApi/BookingsApi.UnitTests/Services/ClonedMultidaysAsynchronousProcessTests.cs, BookingsApi/BookingsApi.UnitTests/Services/PublisherHelperTests.cs, BookingsApi/BookingsApi.UnitTests/Services/SingledayHearingAsynchronousProcessTests.cs, BookingsApi/BookingsApi/Services/HearingParticipantService.cs
Changed the logic to include Judge participant as an existing user
=> VIH-10382 Async Process Changes

BookingsApi/BookingsApi.Infrastructure.Services/HearingAllocationDtoMapper.cs, BookingsApi/BookingsApi.UnitTests/Mappings/V1/HearingAllocationDtoMapperTests.cs
https://tools.hmcts.net/jira/browse/VIH-10412
=> VIH-10412 Removed hearing type from hearing allocation DTO mapper

BookingsApi/BookingsApi.Domain/Person.cs, BookingsApi/BookingsApi/Mappings/V2/ParticipantRequestV2ToNewParticipantMapper.cs
[VIH-10371](https://tools.hmcts.net/jira/browse/VIH-10371)
Admin Web/ Creating a new users are failing a booking
assign username as contact email before creating user in AD
=> VIH-10371 Admin Web Creating a new users are failing a booking 

BookingsApi/BookingsApi.IntegrationTests/Api/V1/Hearings/FailBookingTests.cs, BookingsApi/BookingsApi.IntegrationTests/Api/V1/Hearings/UpdateBookingStatusTests.cs, BookingsApi/BookingsApi/Controllers/V1/HearingsController.cs, charts/vh-bookings-api/values.dev.template.yaml
https://tools.hmcts.net/jira/browse/VIH-10489
When the booking status is updated, the last edited by and confirmed by are being set to UpdateBookingStatusEndpoint, set them to System instead
=> VIH-10489 Set updated and confirmed by to System when updating booking status

BookingsApi/BookingsApi.DAL/Services/HearingService.cs, BookingsApi/BookingsApi.IntegrationTests/Api/V1/HearingParticipants/UpdateHearingParticipantsTests.cs, BookingsApi/BookingsApi.IntegrationTests/Database/Commands/UpdateHearingParticipantsCommandHandlerTests.cs
https://tools.hmcts.net/jira/browse/VIH-10458
=> VIH-10458 Fix - editing the judge does not save the judge name V1

BookingsApi/BookingsApi.Client/BookingsApiClient.cs, BookingsApi/BookingsApi.Contract/V1/Requests/CancelHearingsInGroupRequest.cs, BookingsApi/BookingsApi.IntegrationTests/Api/V1/Hearings/CancelHearingsInGroupTests.cs, BookingsApi/BookingsApi/Controllers/V1/HearingsController.cs, BookingsApi/BookingsApi/Services/BookingService.cs, BookingsApi/BookingsApi/Validations/V1/CancelHearingsInGroupRequestHearingRefDataValidation.cs, BookingsApi/BookingsApi/Validations/V1/CancelHearingsInGroupRequestInputValidation.cs, BookingsApi/BookingsApi/Validations/V1/CancelHearingsInGroupRequestRefDataValidation.cs, BookingsApi/Testing.Common/Builders/Api/ApiUriFactory.cs
https://tools.hmcts.net/jira/browse/VIH-6538
=> VIH-6538 Add endpoint to cancel hearings in group

BookingsApi/BookingsApi.Domain/Hearing.cs, BookingsApi/BookingsApi.IntegrationTests/Api/V1/Hearings/UpdateHearingTests.cs, BookingsApi/BookingsApi.IntegrationTests/Api/V2/Hearings/UpdateHearingV2Tests.cs, BookingsApi/BookingsApi.UnitTests/Domain/Hearing/UpdateHearingDetailsTests.cs
https://tools.hmcts.net/jira/browse/VIH-10461
- Check whether the case details have changed before skipping the update
- Update tests - refactor, read messages for the current hearing only
=> VIH-10461 Fix - edits to case name and number not saved

BookingsApi/BookingsApi.IntegrationTests/Api/V2/Hearings/UpdateHearingsInGroupV2Tests.cs, BookingsApi/BookingsApi/Validations/V2/HearingRequestInputValidationV2.cs, BookingsApi/BookingsApi/Validations/V2/UpdateHearingParticipantsRequestInputValidationV2.cs
https://tools.hmcts.net/jira/browse/VIH-10530
Like when booking a new hearing, only fail validation for the participant counts if there are also no judiciary participants in the request
=> VIH-10530 Fix - Error for enhanced edit of multi-day booking with no participants

BookingsApi/BookingsApi.Contract/V1/Requests/HearingRequest.cs, BookingsApi/BookingsApi.Contract/V2/Requests/HearingRequestV2.cs, BookingsApi/BookingsApi.IntegrationTests/Api/V1/Hearings/UpdateHearingsInGroupTests.cs, BookingsApi/BookingsApi.IntegrationTests/Api/V2/Hearings/UpdateHearingsInGroupV2Tests.cs, BookingsApi/BookingsApi.UnitTests/Validation/V1/UpdateHearingsInGroupRequestValidationTests.cs, BookingsApi/BookingsApi.UnitTests/Validation/V2/UpdateHearingsInGroupRequestValidationV2Tests.cs, BookingsApi/BookingsApi/Controllers/V1/HearingsController.cs, BookingsApi/BookingsApi/Controllers/V2/HearingsControllerV2.cs, BookingsApi/BookingsApi/Validations/V1/HearingRequestValidation.cs, BookingsApi/BookingsApi/Validations/V1/UpdateHearingsInGroupRequestInputValidation.cs, BookingsApi/BookingsApi/Validations/V1/UpdateHearingsInGroupRequestRefDataValidation.cs, BookingsApi/BookingsApi/Validations/V2/HearingRequestInputValidationV2.cs, BookingsApi/BookingsApi/Validations/V2/UpdateHearingsInGroupRequestInputValidationV2.cs, BookingsApi/BookingsApi/Validations/V2/UpdateHearingsInGroupRequestRefDataValidationV2.cs
https://tools.hmcts.net/jira/browse/VIH-9938
- Add additional properties to the request
- Add validation
- For V1 and V2
=> VIH-9938 Update additional details when updating hearings in group

BookingsApi/BookingsApi.Contract/V2/Requests/UpdateParticipantRequestV2.cs, BookingsApi/BookingsApi.DAL/Commands/UpdateParticipantCommand.cs, BookingsApi/BookingsApi.Domain/Participants/Participant.cs, BookingsApi/BookingsApi.Domain/Person.cs, BookingsApi/BookingsApi.IntegrationTests/Api/V1/HearingParticipants/UpdateParticipantDetailsTests.cs, BookingsApi/BookingsApi.IntegrationTests/Api/V2/HearingParticipants/UpdateParticipantDetailsV2Tests.cs, BookingsApi/BookingsApi.IntegrationTests/Database/Commands/UpdateParticipantCommandTests.cs, BookingsApi/BookingsApi.UnitTests/Domain/Participants/UpdateParticipantDetailsTests.cs, BookingsApi/BookingsApi.UnitTests/Validation/V1/UpdateHearingsInGroupRequestValidationTests.cs, BookingsApi/BookingsApi.UnitTests/Validation/V1/UpdateParticipantRequestValidationTests.cs, BookingsApi/BookingsApi.UnitTests/Validation/V2/UpdateHearingsInGroupRequestValidationV2Tests.cs, BookingsApi/BookingsApi.UnitTests/Validation/V2/UpdateParticipantDetailsRequestValidationV2Tests.cs, BookingsApi/BookingsApi/Controllers/V1/HearingParticipantsController.cs, BookingsApi/BookingsApi/Controllers/V2/HearingParticipantsControllerV2.cs, BookingsApi/BookingsApi/Validations/V1/UpdateParticipantRequestValidation.cs, BookingsApi/BookingsApi/Validations/V2/UpdateParticipantRequestValidationV2.cs, BookingsApi/Testing.Common/Builders/Api/V1/Request/UpdateParticipantRequestBuilder.cs
https://tools.hmcts.net/jira/browse/VIH-10490
=> VIH-10490 Change update user account endpoint to optionally update contact email

BookingsApi/BookingsApi.Infrastructure.Services/AsynchronousProcesses/SingledayHearingAsynchronousProcess.cs, BookingsApi/BookingsApi.Infrastructure.Services/Publishers/EventTypes.cs, BookingsApi/BookingsApi.Infrastructure.Services/Publishers/HearingNotificationEventForJudiciaryParticipantPublisher.cs, BookingsApi/BookingsApi.Infrastructure.Services/Publishers/HearingNotificationEventForNewJudicialOfficersPublisher.cs, BookingsApi/BookingsApi.IntegrationTests/Api/V1/Hearings/BookNewHearingTests.cs, BookingsApi/BookingsApi.UnitTests/EventPublisherFactoryInstance.cs, BookingsApi/BookingsApi.UnitTests/Services/BookingServiceTests.cs, BookingsApi/BookingsApi.UnitTests/Services/SingledayHearingAsynchronousProcessTests.cs
[VIH-10536](https://tools.hmcts.net/jira/browse/VIH-10536)
Added Hearing Creation notification email for New Panel Member
=> VIH-10536 - Creating a new Panel member unable to sent notifications

BookingsApi/BookingsApi.Infrastructure.Services/AsynchronousProcesses/NewJudiciaryAddedAsynchronousProcesses.cs, BookingsApi/BookingsApi.Infrastructure.Services/Publishers/HearingNotificationEventForJudiciaryParticipantPublisher.cs, BookingsApi/BookingsApi.IntegrationTests/Api/V1/JudiciaryParticipants/AddJudiciaryParticipantsTests.cs, BookingsApi/BookingsApi.IntegrationTests/Api/V1/JudiciaryParticipants/JudiciaryParticipantApiTest.cs, BookingsApi/BookingsApi.IntegrationTests/Api/V2/HearingParticipants/ReassignJudiciaryJudgeTests.cs
(https://tools.hmcts.net/jira/browse/VIH-10500)
publisher refactored
=> VIH-10500 - Notification for added PM

BookingsApi/BookingsApi.DAL/Commands/ReassignJudiciaryJudgeCommand.cs, BookingsApi/BookingsApi.Domain/JudiciaryParticipant.cs, BookingsApi/BookingsApi.Domain/JudiciaryParticipants/JudiciaryJudge.cs, BookingsApi/BookingsApi.Infrastructure.Services/EventDtoMappers.cs, BookingsApi/BookingsApi.IntegrationTests/Api/V2/HearingParticipants/ReassignJudiciaryJudgeTests.cs, BookingsApi/BookingsApi.IntegrationTests/Helper/TestDataManager.cs, BookingsApi/BookingsApi/Services/JudiciaryParticipantService.cs
[VIH-10577](https://tools.hmcts.net/jira/browse/VIH-10577)
added use of Optional Email
=> VIH-10577 - Notifications sent to generic accounts

BookingsApi/BookingsApi.Common/Services/FeatureToggles.cs, BookingsApi/BookingsApi.DAL/Queries/GetPersonBySearchTermQuery.cs, BookingsApi/BookingsApi.IntegrationTests/Database/Queries/GetPersonBySearchTermQueryHandlerDatabaseTests.cs, BookingsApi/BookingsApi.IntegrationTests/Database/Queries/GetPersonBySearchTermQueryHandlerEFCoreTests.cs, BookingsApi/Testing.Common/Stubs/FeatureTogglesStub.cs, charts/vh-bookings-api/values.dev.template.yaml
https://tools.hmcts.net/jira/browse/VIH-10555
Removed conditional logic around the ejud feature flag
=> VIH-10555 Removed ejud legacy logic

BookingsApi/BookingsApi.Domain/Hearing.cs, BookingsApi/BookingsApi.Domain/Validations/DomainRuleErrorMessages.cs, BookingsApi/BookingsApi.IntegrationTests/Api/V2/HearingParticipants/AddParticipantsToHearingV2Tests.cs, BookingsApi/BookingsApi.UnitTests/Domain/Hearing/AddParticipantTests.cs
VIH-10573
Remove rules stopping addition of interpreters within cut off of changes before the start time
=> VIH-10573 Add interpreter to hearing at any time

BookingsApi/BookingsApi.DAL/Services/HearingAllocationService.cs
https://tools.hmcts.net/jira/browse/VIH-10639
Query optimisations to speed up the retrieval of csos for allocation.
In testing with a copy of the prod db, API response time reduced from ~46s to ~2.2s
=> VIH-10639 Fixes for hearing allocation job failures

BookingsApi/BookingsApi.DAL/Commands/AddParticipantsToVideoHearingCommand.cs, BookingsApi/BookingsApi.DAL/Commands/UpdateHearingParticipantsCommand.cs, BookingsApi/BookingsApi.DAL/Queries/GetAudioRecordedHearingsBySearchQuery.cs, BookingsApi/BookingsApi.Domain/Constants/HearingRoleCodes.cs, BookingsApi/BookingsApi.Domain/Hearing.cs, BookingsApi/BookingsApi.Domain/RefData/CaseType.cs, BookingsApi/BookingsApi.Domain/RefData/HearingRole.cs, BookingsApi/BookingsApi.IntegrationTests/Api/V1/Hearings/GetHearingDetailsByIdTests.cs, BookingsApi/BookingsApi.IntegrationTests/Api/V2/HearingParticipants/AddParticipantsToHearingV2Tests.cs, BookingsApi/BookingsApi.IntegrationTests/Api/V2/HearingParticipants/UpdateHearingParticipantsV2Tests.cs, BookingsApi/BookingsApi.IntegrationTests/Api/V2/Hearings/GetHearingDetailsByIdV2Tests.cs, BookingsApi/BookingsApi.IntegrationTests/Database/Queries/GetAudioRecordedHearingsBySearchQueryHandlerTests.cs, BookingsApi/BookingsApi.IntegrationTests/Features/V1/SearchHearings.feature, BookingsApi/BookingsApi.IntegrationTests/Helper/SeedVideoHearingOptions.cs, BookingsApi/BookingsApi.IntegrationTests/Helper/TestDataManager.cs, BookingsApi/BookingsApi.IntegrationTests/Steps/CommonSteps.cs, BookingsApi/BookingsApi.IntegrationTests/Steps/HearingsSteps.cs, BookingsApi/BookingsApi.UnitTests/Controllers/HearingsController/SearchForHearingsTests.cs, BookingsApi/BookingsApi.UnitTests/Domain/CaseTypes/SupportsAudioRecordingTests.cs, BookingsApi/BookingsApi.UnitTests/Domain/Hearing/AddParticipantTests.cs, BookingsApi/BookingsApi/Controllers/V1/HearingsController.cs
VIH-10642
set AudioRecordingRequired to true in the domain if an interpreter is added and the case type supports it
=> VIH-10642 bug fix when interpreter is added close to start time

BookingsApi/BookingsApi.IntegrationTests/Api/V1/HearingParticipants/UpdateParticipantDetailsTests.cs, BookingsApi/BookingsApi.IntegrationTests/Api/V2/HearingParticipants/UpdateParticipantDetailsV2Tests.cs, BookingsApi/BookingsApi.UnitTests/Validation/V1/RepresentativeValidationTests .cs, BookingsApi/BookingsApi/Validations/Common/RepresentativeValidation.cs
VIH-10611
make the organisation field optional in API requests
=> VIH-10611 make the organisation field optional in API requests

BookingsApi/BookingsApi.Client/BookingsApi.Client.csproj, BookingsApi/BookingsApi.Contract/BookingsApi.Contract.csproj
VIH-10125
Have clients target .net standard and .net 8
=> VIH-10125 target netstandard for client project

BookingsApi/BookingsApi.DAL/Exceptions/BookingsDalException.cs, BookingsApi/BookingsApi.DAL/Exceptions/EndPointNotFoundException.cs, BookingsApi/BookingsApi.DAL/Exceptions/HearingNotFoundException.cs, BookingsApi/BookingsApi.DAL/Exceptions/JudiciaryPersonNotFoundException.cs, BookingsApi/BookingsApi.DAL/Exceptions/JusticeUserNotFoundException.cs, BookingsApi/BookingsApi.DAL/Exceptions/NonWorkingHoursNotFoundException.cs, BookingsApi/BookingsApi.DAL/Exceptions/ParticipantNotFoundException.cs, BookingsApi/BookingsApi.DAL/Exceptions/PersonNotFoundException.cs, BookingsApi/BookingsApi.DAL/Queries/GetVhoWorkHoursQuery.cs, BookingsApi/BookingsApi.IntegrationTests/Database/Queries/GetVhoWorkHoursQueryHandlerDatabaseTests.cs, BookingsApi/BookingsApi.UnitTests/Controllers/HearingParticipantsController/GetAllParticipantsInHearingTests.cs, BookingsApi/BookingsApi.UnitTests/Controllers/Persons/AnonymisePersonWithUsernameForExpiredHearingsTests.cs, BookingsApi/BookingsApi.UnitTests/Controllers/Persons/UpdatePersonDetailsTests.cs, BookingsApi/BookingsApi.UnitTests/Middleware/ExceptionMiddlewareTests.cs, BookingsApi/BookingsApi/Controllers/V1/EndPointsController.cs, BookingsApi/BookingsApi/Controllers/V1/HearingParticipantsController.cs, BookingsApi/BookingsApi/Controllers/V1/JudiciaryParticipantsController.cs, BookingsApi/BookingsApi/Controllers/V1/JusticeUserController.cs, BookingsApi/BookingsApi/Controllers/V1/PersonsController.cs, BookingsApi/BookingsApi/Controllers/V1/WorkHoursController.cs, BookingsApi/BookingsApi/Extensions/ExceptionMiddleware.cs
VIH-10726
* Make GetVhoWorkAvailabilityHours query throw a JusticeUserNotFoundException if not found
* Migrate not found exceptions to extend the EntityNotFoundException to handle all not found scenarios with a 404
=> VIH-10726 Refactor exception handling out of controller into the middleware

BookingsApi/BookingsApi.AcceptanceTests/Api/V1/RefData/InterpreterLanguageTests.cs, BookingsApi/BookingsApi.Client/BookingsApiClient.cs, BookingsApi/BookingsApi.Contract/BookingsApi.Contract.csproj, BookingsApi/BookingsApi.Contract/V1/Enums/InterpreterType.cs, BookingsApi/BookingsApi.Contract/V1/Responses/InterpreterLanguagesResponse.cs, BookingsApi/BookingsApi.DAL/BookingsDbContext.cs, BookingsApi/BookingsApi.DAL/Mappings/InterpreterLanguageMap.cs, BookingsApi/BookingsApi.DAL/Migrations/20240613142338_AddInterepreterLanguage.Designer.cs, BookingsApi/BookingsApi.DAL/Migrations/20240613142338_AddInterepreterLanguage.cs, BookingsApi/BookingsApi.DAL/Queries/GetInterpreterLanguages.cs, BookingsApi/BookingsApi.Domain/RefData/InterpreterLanguage.cs, BookingsApi/BookingsApi.IntegrationTests/Api/V1/InterpreterLanguages/GetAvailableInterpreterLanguageTests.cs, BookingsApi/BookingsApi/Controllers/V1/InterpreterLanguagesController.cs, BookingsApi/BookingsApi/Mappings/V1/InterpreterLanguageToResponseMapper.cs, RefData/Migrations/20240613144455_AddInterpreterLanguages.Designer.cs, RefData/Migrations/20240613144455_AddInterpreterLanguages.cs, RefData/data/10742_add_interpreter_languages.sql
VIH-10742
Add Interpreter languages ref data
=> VIH-10742 Add interpreter languages ref data

BookingsApi/BookingsApi.DAL/Mappings/JudiciaryPersonMap.cs, BookingsApi/BookingsApi.DAL/Migrations/20240708125739_RemoveUniqueConstrainOnJudiciaryPersonExtneralRefId.Designer.cs, BookingsApi/BookingsApi.DAL/Migrations/20240708125739_RemoveUniqueConstrainOnJudiciaryPersonExtneralRefId.cs
VIH-10785
* remove unique constraint on ExternalRefId for JudiciaryPerson
=> VIH-10785 remove unique constraint on ExternalRefId for JudiciaryPerson

BookingsApi/BookingsApi.AcceptanceTests/appsettings.json, BookingsApi/BookingsApi.Common/Configuration/KinlyConfiguration.cs, BookingsApi/BookingsApi.Common/Configuration/SupplierConfiguration.cs, BookingsApi/BookingsApi.Common/Services/FeatureToggles.cs, BookingsApi/BookingsApi.IntegrationTests/ApiTest.cs, BookingsApi/BookingsApi.IntegrationTests/BookingsApi.IntegrationTests.csproj, BookingsApi/BookingsApi.IntegrationTests/Database/DatabaseTestsBase.cs, BookingsApi/BookingsApi.IntegrationTests/Helper/TestDataManager.cs, BookingsApi/BookingsApi.IntegrationTests/Hooks/ConfigHooks.cs, BookingsApi/BookingsApi.IntegrationTests/Services/EndpointService/GetSipAddressStemTests.cs, BookingsApi/BookingsApi.IntegrationTests/appsettings.json, BookingsApi/BookingsApi.IntegrationTests/packages.lock.json, BookingsApi/BookingsApi.UnitTests/Controllers/HearingsController/BookNewHearingTests.cs, BookingsApi/BookingsApi.UnitTests/Controllers/HearingsController/HearingsControllerTests.cs, BookingsApi/BookingsApi/Controllers/V1/EndPointsController.cs, BookingsApi/BookingsApi/Controllers/V1/HearingsController.cs, BookingsApi/BookingsApi/Controllers/V2/HearingsControllerV2.cs, BookingsApi/BookingsApi/Services/EndpointService.cs, BookingsApi/BookingsApi/Services/UpdateHearingService.cs, BookingsApi/BookingsApi/Startup.cs, BookingsApi/Testing.Common/Stubs/FeatureTogglesStub.cs, charts/vh-bookings-api/Chart.yaml, charts/vh-bookings-api/values.yaml
VIH-10826
include the vodafone sip address stem configuration and decide based on the Vodafone toggle
=> VIH-10826 include vodafone sip address stem configuration

BookingsApi/BookingsApi.AcceptanceTests/packages.lock.json, BookingsApi/BookingsApi.Infrastructure.Services/BookingsApi.Infrastructure.Services.csproj, BookingsApi/BookingsApi.Infrastructure.Services/ServiceBusQueue/ServiceBusQueueClient.cs, BookingsApi/BookingsApi.IntegrationTests/packages.lock.json, BookingsApi/BookingsApi.UnitTests/packages.lock.json, BookingsApi/BookingsApi/packages.lock.json
https://tools.hmcts.net/jira/browse/VIH-10819
- Upgrade service bus sdk (move from deprecated Microsoft.Azure.ServiceBus to Azure.Messaging.ServiceBus)
- General tidy up - convert to primary constructor, remove redundant usings/setter
=> VIH-10819 Upgrade service bus sdk

charts/vh-bookings-api/Chart.yaml, charts/vh-bookings-api/values.yaml
VIH-10826
remove obsolete chart value
=> VIH-10826 remove obsolete chart value

BookingsApi/BookingsApi.Contract/V2/Requests/BookNewHearingRequestV2.cs, BookingsApi/BookingsApi.IntegrationTests/Api/V2/Hearings/BookNewHearingV2Tests.cs, BookingsApi/BookingsApi/Controllers/V2/HearingsControllerV2.cs
VIH-10885
Make BookingSupplier and optional property in BookNewHearingRequestV2.cs
=> VIH-10885 Make BookingSupplier an optional property

BookingsApi/BookingsApi.IntegrationTests/Services/EndpointService/GetSipAddressStemTests.cs, BookingsApi/BookingsApi/Controllers/V1/EndPointsController.cs, BookingsApi/BookingsApi/Controllers/V1/HearingsController.cs, BookingsApi/BookingsApi/Controllers/V2/HearingsControllerV2.cs, BookingsApi/BookingsApi/Services/EndpointService.cs, BookingsApi/BookingsApi/Services/UpdateHearingService.cs
VIH-10807
* use the conference supplier property where possible and then default to vodafone toggle if not present
=> VIH-10807 use supplier property first and then default to vodafone toggle to get sip address stem

.github/CODEOWNERS, azure-pipelines.sds.master-release.yml
See [VIH-10889](https://tools.hmcts.net/jira/browse/VIH-10889)
Change description
Corrects pipeline YAML indentation
=> VIH-10889 include demo env for auto deploy

BookingsApi/BookingsApi.Common/ApplicationLogger.cs, BookingsApi/BookingsApi.DAL/Services/HearingService.cs, BookingsApi/BookingsApi.Domain/Hearing.cs, BookingsApi/BookingsApi.UnitTests/Domain/Hearing/AddParticipantTests.cs
VIH-10900
Skip existing person validation/check if contact email is null
=> VIH-10900 bug fix add multiple participants with no contact email

azure-pipelines.sds.release.yml, variables/ithc.yaml
See [VIH-10920](https://tools.hmcts.net/jira/browse/VIH-10920)
add EF_Run_Entity_Framework_ITHC stage
=> VIH-10920 add EF_Run_Entity_Framework_ITHC stage

azure-pipelines.sds.master-release.yml, variables/dev.yaml, variables/test.yaml
See [VIH-10983](https://tools.hmcts.net/jira/browse/VIH-10983)
Refactor non-prod master release pipeline to allow separate image build & ad-hoc deploy to specific environments.
Tested that pipeline works as expected, and images are built and pushed with the relevant tag.
=> VIH-10983 refactor non-prod master deployment pipeline

RefData/Migrations/20241004070055_AddInterpreterLanguagesWelsh.cs, RefData/data/10837_update_interpreter_languages_welsh.sql
[VIH-10837](https://tools.hmcts.net/jira/browse/VIH-10837)
Added migration
=> VIH-10837 Apply welsh translations to remaining interpreter languages

RefData/Migrations/20241015150655_AddEnglishInterpreterLanguage.cs, RefData/data/10825_addenglish_interpreter_languages.sql
[VIH-10825](https://tools.hmcts.net/jira/browse/VIH-10825)
Added migration
=> VIH-10825 add english to interpreter languages

BookingsApi/BookingsApi.IntegrationTests/Api/V1/Endpoints/RemoveEndPointFromHearingTests.cs, BookingsApi/BookingsApi.IntegrationTests/Api/V1/HearingParticipants/UpdateParticipantDetailsTests.cs, BookingsApi/BookingsApi.IntegrationTests/Api/V1/Hearings/UpdateHearingsInGroupTests.cs, BookingsApi/BookingsApi.IntegrationTests/Api/V2/Endpoints/AddEndPointToHearingV2Tests.cs, BookingsApi/BookingsApi.IntegrationTests/Api/V2/Endpoints/UpdateEndpointV2Tests.cs, BookingsApi/BookingsApi.IntegrationTests/Api/V2/Hearings/UpdateHearingsInGroupV2Tests.cs, BookingsApi/BookingsApi.UnitTests/Controllers/HearingParticipantsController/AddParticipantsToHearingTests.cs, BookingsApi/BookingsApi.UnitTests/Controllers/HearingParticipantsController/HearingParticipantsControllerTest.cs, BookingsApi/BookingsApi.UnitTests/Controllers/HearingParticipantsController/RemoveParticipantFromHearingTests.cs, BookingsApi/BookingsApi/Controllers/V1/HearingParticipantsController.cs, BookingsApi/BookingsApi/Services/EndpointService.cs, BookingsApi/BookingsApi/Services/HearingParticipantService.cs
VIH-11042
This pull request includes several changes to enhance the handling of integration events in the `BookingsApi` project, particularly focusing on the `HearingParticipantsController` and related services. The changes ensure that appropriate events are published when participants and endpoints are added, updated, or removed, and refactor some existing code to improve maintainability.
* Publish the HearingDetailsUpdatedIntegrationEvent when the participant/endpoint list changes to re-calculate the room type (screening requirements may change and as a result change the room type)
=> VIH-11042 publish hearing details when participant or endpoints change

BookingsApi/BookingsApi.DAL/Queries/GetHearingsByUsernameForDeletionQuery.cs
[VIH-10049](https://tools.hmcts.net/jira/browse/VIH-10049)
added ordering descending by date
=> VIH-10049 display hearings sorted by date in the delete user page

BookingsApi/BookingsApi.Infrastructure.Services/EndpointDtoMapper.cs, BookingsApi/BookingsApi.Infrastructure.Services/HearingDtoMapper.cs, BookingsApi/BookingsApi.IntegrationTests/Api/V2/Endpoints/AddEndPointToHearingV2Tests.cs, BookingsApi/BookingsApi.IntegrationTests/Api/V2/Hearings/BookNewHearingV2Tests.cs, BookingsApi/BookingsApi.UnitTests/Extensions/EndpointExtensions.cs
VIH-11152
Endpoint role should be GUEST when hearing room type is a VMR
=> VIH-11152 Endpoint role should be GUEST when hearing room type is a VMR

BookingsApi/BookingsApi.IntegrationTests/Api/V2/Hearings/BookNewHearingV2Tests.cs, BookingsApi/BookingsApi/Controllers/V2/HearingsControllerV2.cs
VIH-10996
If the vodafone toggle is off, the booking supplier should reset to Kinly at booking
=> VIH-10996 reset booking supplier to kinly if vodafone feature toggle is off

BookingsApi/BookingsApi.IntegrationTests/Steps/HearingsSteps.cs, RefData/Migrations/20241120150655_AddUpperTribunals.cs, RefData/data/11105_mrd_add_case_types_upper_tribunals.sql
[VIH-11105](https://tools.hmcts.net/jira/browse/VIH-11105)
Add Jurisdiction Upper Tribunal Tax and Chancery Chamber  
Add CaseType linked to the new Jurisdiction
=> VIH-11105 - Add MRD upper tribunal services to VH

azure-pipelines.sds.master-release.yml, variables/demo.yaml
See VIH-11181](https://tools.hmcts.net/jira/browse/VIH-11181)
enable demo image and helm build & push
=> VIH-11181 enable demo image buildpush

RefData/Migrations/20241121145559_AddExpiringDateToCaseTypes.cs, RefData/data/11107_add_case_types_expiration_dates.sql
[VIH-11107](https://tools.hmcts.net/jira/browse/VIH-11107)
Updated expiration date
=> VIH-11107 Expire MRD case types in lower environments 

RefData/Migrations/20241122150655_CaseTypesExpiringDate.cs, RefData/data/11108_mrd_case_types_expiring_date.sql
[VIH-11108](https://tools.hmcts.net/jira/browse/VIH-11108)
update expiring date
=> VIH-11108 Expire upper tribunal case types

RefData/Migrations/20241120150655_RenameCaseTypes.cs, RefData/data/11111_mrd_case_types_amend_names.sql
[VIH-11111](https://tools.hmcts.net/jira/browse/VIH-11111)
renamed case types
=> VIH-11111 Amend MRD services on VH

RefData/Migrations/20241128150655_RenameCaseTypes.cs, RefData/Migrations/20241128150655_RevertCaseTypes.cs, RefData/data/11185_mrd_case_types_amend_names.sql
[VIH-11185](https://tools.hmcts.net/jira/browse/VIH-11185)
Reverted names in case types
=> VIH-11185 revert changes as confirmed by mrd

RefData/Migrations/20241125150655_AddEmplymentAppeals.cs, RefData/Migrations/20241125160655_AddJurisdictions.cs, RefData/Migrations/20241128160655_AddUpperTribunalLandsChamber.cs, RefData/data/11173_mrd_add_case_types_Employment_Appeals.sql, RefData/data/11173_mrd_add_case_types_Upper_Tribunal_Lands_Chamber.sql, RefData/data/11173_mrd_update_case_types_with_Jurisdiction.sql
[VIH-11173](https://tools.hmcts.net/jira/browse/VIH-11173)
add Jurisdiction Employment Appeals Tribunal
update case types
=> VIH-11173 add Jurisdiction and update case types

BookingsApi/BookingsApi.DAL/Commands/UpdateEndPointOfHearingCommand.cs, BookingsApi/BookingsApi.DAL/Commands/UpdateHearingCommand.cs, BookingsApi/BookingsApi.DAL/Commands/UpdateHearingParticipantsCommand.cs, BookingsApi/BookingsApi.IntegrationTests/Database/Commands/UpdateEndPointOfHearingCommandTests.cs, BookingsApi/BookingsApi/Controllers/V2/EndpointsControllerV2.cs, BookingsApi/BookingsApi/Services/EndpointService.cs, BookingsApi/BookingsApi/Services/UpdateHearingService.cs
VIH-11190
* Assign external ref id for endpoints on update
* Include split query on slow performing queries
* Minimise rows returned on participant update query when applying language codes
=> VIH-11190 external ref id missing for endpoints

BookingsApi/BookingsApi.AcceptanceTests/packages.lock.json, BookingsApi/BookingsApi.IntegrationTests/Api/V1/JudiciaryPersons/BulkJudiciaryPersonsTests.cs, BookingsApi/BookingsApi.IntegrationTests/Api/V1/JudiciaryPersons/PostJudiciaryPersonBySearchTermTests.cs, BookingsApi/BookingsApi.IntegrationTests/Api/V1/JusticeUsers/AddJusticeUserTests.cs, BookingsApi/BookingsApi.IntegrationTests/Api/V2/Hearings/UpdateHearingV2Tests.cs, BookingsApi/BookingsApi.IntegrationTests/Api/V2/Hearings/UpdateHearingsInGroupV2Tests.cs, BookingsApi/BookingsApi.IntegrationTests/BookingsApi.IntegrationTests.csproj, BookingsApi/BookingsApi.IntegrationTests/Helper/TestDataManager.cs, BookingsApi/BookingsApi.IntegrationTests/packages.lock.json, BookingsApi/BookingsApi.UnitTests/DAL/Commands/AddJudiciaryPersonStagingCommandTests.cs, BookingsApi/BookingsApi.UnitTests/DAL/Commands/AnonymiseCaseAndParticipantCommandTests.cs, BookingsApi/BookingsApi.UnitTests/DAL/Queries/GetAnonymisationDataQueryHandlerTests.cs, BookingsApi/BookingsApi.UnitTests/Domain/Persons/AnonymisePersonWithUsernameCommandTests.cs, BookingsApi/BookingsApi.UnitTests/Validation/V1/AddJusticeUserRequestValidationTests.cs, BookingsApi/BookingsApi.UnitTests/Validation/V2/UpdateHearingRequestValidationV2Tests.cs, BookingsApi/BookingsApi.UnitTests/packages.lock.json, BookingsApi/Testing.Common/Builders/Api/V2/ParticipantRequestBuilderV2.cs, BookingsApi/Testing.Common/Builders/Api/V2/SimpleBookNewHearingRequestV2.cs, BookingsApi/Testing.Common/Builders/Domain/JudiciaryPersonBuilder.cs, BookingsApi/Testing.Common/Builders/Domain/PersonBuilder.cs, BookingsApi/Testing.Common/Testing.Common.csproj
[VIH-11091](https://tools.hmcts.net/jira/browse/VIH-11091)
removed Faker.NetCore and replaced with Bogus
=> VIH-11091 - replace Faker.NetCore with Bogus

.github/workflows/launch-darkly-find-code-refs-in-pr.yml, .github/workflows/launch-darkly-flag-sync.yml, .github/workflows/osv-scanner-pr.yml
VIH-11246
Update to the GitHub Actions:
* Switch the full LD code scan to run against master only and on a schedule
* Add the LD code scan on diff to run against PRs only
* Turn off fail on vuln for OSV scanner
=> VIH-11246 turn off fail on vuln for OSV scanner

.github/renovate.json
VIH-11252
add renovate job for Helm Chart Release function
=> VIH-11252 add renovate job for Helm Chart Release function

BookingsApi/BookingsApi.DAL/Commands/UpdateHearingParticipantsCommand.cs, BookingsApi/BookingsApi.Domain/Hearing.cs, BookingsApi/BookingsApi.Domain/SpecialMeasure/Screening.cs, BookingsApi/BookingsApi.IntegrationTests/Api/V2/HearingParticipants/UpdateHearingParticipantsV2Tests.cs, BookingsApi/BookingsApi.UnitTests/Domain/Screenings/RemoveEndpointTests.cs, BookingsApi/BookingsApi.UnitTests/Domain/Screenings/RemoveParticipantTests.cs
https://tools.hmcts.net/jira/browse/VIH-11259
If participant with a screening is removed the screening entities on their screening needs to be cleared, or we'll trigger the domain rule exception, when looping through to delete dependencies in the Screening.Remove function
=> VIH-11259 Error removing participant from hearing with screening

BookingsApi/BookingsApi.Infrastructure.Services/Dtos/JusticeUserDto.cs, BookingsApi/BookingsApi.Infrastructure.Services/JusticeUserDtoMapper.cs, BookingsApi/BookingsApi.IntegrationTests/Api/V1/WorkAllocation/AllocateHearingManuallyTests.cs
VIH-11301
VIH-11269
provide the justice name in the allocation update to avoid additional api calls in video web to get the display name
=> VIH-11301 provide the justice name in the allocation update to avoid additional api calls

charts/vh-bookings-api/Chart.yaml, charts/vh-bookings-api/values.dev.template.yaml, charts/vh-bookings-api/values.yaml
Jira link
https://tools.hmcts.net/jira/browse/VIH-11295
Change description
Use latest Java base chart version so Azure Workload Identity is used
=> VIH-11295 update chart
