BookingsAPI/Bookings.DAL/Migrations/20190315100721_AddOtherInformationToHearing.cs, BookingsAPI/Bookings.DAL/SeedData/SeedCaseTypesData.cs, BookingsAPI/Bookings.Domain/Enumerations/CaseRoleGroup.cs
[VIH-4510](https://tools.hmcts.net/jira/browse/VIH-4510)
The CaseRoleGroups enum values have been renamed to be meaningful. At the moment when a booking is queued, the data for party groups are not representative of the case type and role
```
[ ] Yes
[x] No
```
=> rename CaseRoleGroup enum values to correct values

BookingsAPI/Bookings.DAL/Queries/GetParticipantWithSuitabilityAnswersQuery.cs, BookingsAPI/Bookings.IntegrationTests/Steps/SuitabilityAnswersSteps.cs
Fix cursor problem to get suitability answer list
```
[ ] Yes
[ X] No
```
=> fix cursor of request for suitability answers

BookingsAPI/Bookings.AcceptanceTests/Models/AddParticipantRequest.cs, BookingsAPI/Bookings.AcceptanceTests/Steps/HearingsSteps.cs, BookingsAPI/Bookings.AcceptanceTests/Steps/ParticipantsSteps.cs, BookingsAPI/Testing.Common/Builders/Api/Request/ParticipantRequestBuilder.cs, BookingsAPI/Testing.Common/Builders/Domain/PersonBuilder.cs
Added more prefixes so all created users are not prefixed with "Automation_" to make them easily identifiable in AAD, and thus easy to cleanup at a later date.
```
[ ] Yes
[X] No
```
=> Added more test data prefixes

BookingsApi/BookingsApi.DAL/Commands/RemoveHearingCommand.cs
https://tools.hmcts.net/jira/browse/VIH-7401
protecting the RemoveHearing Command against a null LinkedParticipant array
```
[ ] Yes
[X ] No
```
=> VIH-7401 guard against null LinkedparticipantArray

BookingsApi/BookingsApi.DAL/Commands/RemoveHearingCommand.cs, BookingsApi/BookingsApi.IntegrationTests/Database/Commands/RemoveHearingCommandTests.cs
https://tools.hmcts.net/jira/browse/VIH-7401
A test has been added for RemoveHearingCommand when the hearing contains linked participants
The RemoveHearingCommand now removes all linked participants entries, saves the context and then continues processing the removal of the hearing and participants 
```
[ ] Yes
[ ] No
```
=> VIH-7401 fix Remove Hearing with linked participants 

BookingsApi/BookingsApi.DAL/Commands/RemoveHearingCommand.cs, BookingsApi/BookingsApi.IntegrationTests/Helper/TestDataManager.cs
https://tools.hmcts.net/jira/browse/VIH-7465
Modified the RemoveHearingCommand so that the linked participant removal is now an line RemoveRange call and LinkedParticipants are retrieved after Participants in the original query instead of as the last Include.
Also modified the TestDataManager so that the Linked participant creation is all performed within the static method instead of half in and half out.
```
[ ] Yes
[ X] No
```
=> VIH-7465 fix removal of hearing

BookingsApi/BookingsApi.DAL/Commands/UpdateHearingParticipantsCommand.cs, BookingsApi/BookingsApi.DAL/Queries/GetPersonBySearchTermQuery.cs, BookingsApi/BookingsApi.IntegrationTests/Database/Queries/GetPersonBySearchTermQueryHandlerDatabaseTests.cs
VIH-8081
Clearing linked participant list rather than using hearing service which breaks when a linked participant has already been moved. EDIT: This now includes a fix for an intermittently failing integration test.
```
[ ] Yes
[x] No
```
=> VIH-8081 remove interpreter causes error

BookingsApi/BookingsApi.DAL/BookingsDbContext.cs, BookingsApi/BookingsApi.DAL/Commands/AddParticipantsToVideoHearingCommand.cs, BookingsApi/BookingsApi.DAL/Commands/CreateVideoHearingCommand.cs, BookingsApi/BookingsApi.DAL/Commands/UpdateHearingParticipantsCommand.cs, BookingsApi/BookingsApi.DAL/Commands/UpdateParticipantCommand.cs, BookingsApi/BookingsApi.DAL/Helper/HearingRoles.cs, BookingsApi/BookingsApi.DAL/Services/HearingService.cs, BookingsApi/BookingsApi.IntegrationTests/Database/Commands/AddParticipantsToVideoHearingCommandTests.cs, BookingsApi/BookingsApi.IntegrationTests/Database/Commands/CreateVideoHearingCommandTests.cs, BookingsApi/BookingsApi.IntegrationTests/Database/Commands/UpdateHearingParticipantsCommandHandlerTests.cs, BookingsApi/BookingsApi.IntegrationTests/Database/Commands/UpdateParticipantCommandTests.cs, BookingsApi/BookingsApi.IntegrationTests/Helper/TestDataManager.cs, BookingsApi/BookingsApi.UnitTests/Controllers/HearingsController/HearingsControllerTests.cs, BookingsApi/BookingsApi.UnitTests/Mappings/ParticipantToResponseMapperTests.cs, BookingsApi/BookingsApi/ConfigureServicesExtensions.cs, BookingsApi/BookingsApi/Controllers/HearingsController.cs, BookingsApi/Testing.Common/Builders/Domain/HearingRoleIds.cs, BookingsApi/Testing.Common/Builders/Domain/VideoHearingBuilder.cs
* Fixed bug where the judge couldn't be changed
* Removed test code
* Removed auto generated fully qualified import
* Removed unit tests for hearing service as it was causing issues when running the app due to requiring a parameterless constructor when instantiating the BookingsDbContext
* Same as last commit but missed a bit
* Dummy change to try to fix pipeline not triggering
* Set RunSonarCloudTests to false to test pipeline failure
* Reverted last commit
* Extracted test hearing roles to their own class
```
[ ] Yes
[ ] No
```
=> VIH-8458 Fixed judge change causing exception (#334)

azure-pipelines.sds.release.yml
VIH-8951
Update Pipeline to use Build.SourceBranch instead of Build.SourceBranchName
This is required for the Pipeline to work as expected.
Build.SourceBranchName = branchname
Build.SourceBranch           = refs/heads/branchname
```
[ ] Yes
[ X ] No
```
=> VIH-8951 - Update Release Pipeline

BookingsApi/BookingsApi.Contract/Requests/JudiciaryPersonRequest.cs, BookingsApi/BookingsApi.DAL/Commands/AddJudiciaryPersonByExternalRefIdCommand.cs, BookingsApi/BookingsApi.DAL/Commands/AddJudiciaryPersonCommand.cs, BookingsApi/BookingsApi.DAL/Commands/JudiciaryLeaverCommandBase.cs, BookingsApi/BookingsApi.DAL/Commands/JudiciaryPersonCommandBase.cs, BookingsApi/BookingsApi.DAL/Commands/UpdateJudiciaryLeaverByExternalRefIdCommand.cs, BookingsApi/BookingsApi.DAL/Commands/UpdateJudiciaryPersonByExternalRefIdCommand.cs, BookingsApi/BookingsApi.DAL/Commands/UpdateJudiciaryPersonCommandBase.cs, BookingsApi/BookingsApi.DAL/Migrations/20220616100009_ChangeJudiciaryPersonExternalRefIdToString.Designer.cs, BookingsApi/BookingsApi.DAL/Migrations/20220616100009_ChangeJudiciaryPersonExternalRefIdToString.cs, BookingsApi/BookingsApi.DAL/Queries/GetJudiciaryPersonByExternalRefIdQuery.cs, BookingsApi/BookingsApi.Domain/JudiciaryPerson.cs, BookingsApi/BookingsApi.IntegrationTests/Database/Commands/AddJudiciaryPersonByExternalRefIdCommandTests.cs, BookingsApi/BookingsApi.IntegrationTests/Database/Commands/AddJudiciaryPersonCommandTests.cs, BookingsApi/BookingsApi.IntegrationTests/Database/Commands/UpdateJudiciaryLeaverByExternalRefIdCommandTests.cs, BookingsApi/BookingsApi.IntegrationTests/Database/Commands/UpdateJudiciaryPersonByExternalRefIdCommandTests.cs, BookingsApi/BookingsApi.IntegrationTests/Helper/TestDataManager.cs, BookingsApi/BookingsApi.IntegrationTests/Steps/JudiciaryPersonsSteps.cs, BookingsApi/BookingsApi.UnitTests/Controllers/JudiciaryPersonControllerTests.cs, BookingsApi/BookingsApi.UnitTests/Domain/JudiciaryPersons/UpdateJudiciaryPersonTests.cs, BookingsApi/BookingsApi/Controllers/JudiciaryPersonController.cs, BookingsApi/Testing.Common/Builders/Domain/JudiciaryPersonBuilder.cs, azure-pipelines.yml
https://tools.hmcts.net/jira/browse/VIH-9109
Sometimes the deserialisation of the eLinks People API response fails, this is because the Id is a uuid and we are casting it to a Guid.
Instead, store it as string.
```
[ ] Yes
[x] No
```
=> VIH-9109 Fix issue parsing JudiciaryPerson Id

BookingsApi/BookingsApi.UnitTests/Mappings/ParticipantRequestToNewParticipantMapperTest.cs, BookingsApi/BookingsApi/Mappings/ParticipantRequestToNewParticipantMapper.cs
https://tools.hmcts.net/jira/browse/VIH-9161
Fixes an issue where upon creating a new user as part of a booking, the user is not added into any AD groups.
This is due to the username being set to the contact email, resulting in a failed Azure AD lookup.
```
[ ] Yes
[x] No
```
=> VIH-9161 Fix issue with users not being added to AD groups

BookingsApi/BookingsApi.Infrastructure.Services/Dtos/HearingDto.cs, BookingsApi/BookingsApi.Infrastructure.Services/HearingDtoMapper.cs
Fix for populating hearing type used in sending the notification
```
[ ] Yes
[x ] No
```
=> VIH-8884 Populating hearing type name

BookingsApi/BookingsApi.UnitTests/Controllers/HearingParticipantsController/UpdateHearingParticipantsTests.cs, BookingsApi/BookingsApi/Controllers/HearingParticipantsController.cs
https://tools.hmcts.net/jira/browse/VIH-9228
Fixes an issue where removing participants from a hearing removes them from bookings API but not video API.
This is due to the hearing participants updated event not being published in this scenario.
```
[ ] Yes
[x] No
```
=> VIH-9228 Unable to remove party from hearing

BookingsApi/BookingsApi.IntegrationTests/Features/Persons.feature, BookingsApi/BookingsApi.IntegrationTests/Helper/TestDataManager.cs, BookingsApi/BookingsApi.IntegrationTests/Steps/PersonsSteps.cs, BookingsApi/BookingsApi/Controllers/PersonsController.cs, BookingsApi/Testing.Common/Builders/Api/ApiUriFactory.cs, BookingsApi/Testing.Common/Builders/Domain/PersonBuilder.cs
https://tools.hmcts.net/jira/browse/VIH-9257
Creating a hearing with participants containing slashes in their email address currently fails as the slash doesn't get url decoded, causing the user lookups to fail.
Fix by changing the contactEmail to a catch-all parameter (**) which supports slashes.
```
[ ] Yes
[x] No
```
=> VIH-9257 Support slashes in email addresses

BookingsApi/BookingsApi.UnitTests/Controllers/HearingsController/BookNewHearingTests.cs, BookingsApi/BookingsApi/Controllers/HearingsController.cs
https://tools.hmcts.net/jira/browse/VIH-9336
Trims whitespace from a participant's first and last name to avoid validation failures creating a booking
```
[ ] Yes
[x] No
```
=> VIH-9336 Fix for booking failing for participants with names starting or ending with spaces

BookingsApi/BookingsApi.Common/Services/FeatureToggles.cs, BookingsApi/BookingsApi.Contract/Configuration/FeatureFlagConfiguration.cs, BookingsApi/BookingsApi.DAL/Queries/GetPersonBySearchTermQuery.cs, BookingsApi/BookingsApi.IntegrationTests/Database/Queries/GetPersonBySearchTermQueryHandlerDatabaseTests.cs, BookingsApi/BookingsApi.IntegrationTests/Database/Queries/GetPersonBySearchTermQueryHandlerEFCoreTests.cs, BookingsApi/BookingsApi.UnitTests/DAL/Services/FeatureFlagServiceTests.cs, BookingsApi/BookingsApi/Services/FeatureFlagService.cs, azure-pipelines.release.yml, azure-pipelines.yml
https://tools.hmcts.net/jira/browse/VIH-9417
Toggles eJud feature moved to Launch Darkly:
Updated the pipelines so they no longer pass in the eJud setting
Updated acceptance tests
=> VIH-9417 - Toggle eJudFeature moved to Launch Darkly Updated the pipeline

BookingsApi/BookingsApi.DAL/Services/HearingService.cs
https://tools.hmcts.net/jira/browse/VIH-9397
Some of the properties returned by the Get Unallocated Hearings query are not populated, this causes an error when the API tries to map to a DTO.
Fix by Adding `.Include` to populate these properties
```
[ ] Yes
[x] No
```
=> VIH-9397 Populate unmapped properties for get unallocated hearings

BookingsApi/BookingsApi.Domain/JusticeUser.cs, BookingsApi/BookingsApi.UnitTests/DAL/Services/HearingAllocationServiceTests.cs
https://tools.hmcts.net/jira/browse/VIH-9394
Consider a user to be unavailable for allocation if their work hours are outside the hearing times (ie they start and finish before the hearing starts, or start and finish after the hearing ends).
Adds test to ensure that this applies regardless of the allocation settings (allowing hearing to start before work start time = true or false, allow hearing to end after work end time = true or false).
```
[ ] Yes
[x] No
```
=> VIH-9394 Update user availability logic

BookingsApi/BookingsApi.Client/BookingsApiClient.cs, BookingsApi/BookingsApi.Contract/Enums/BookingStatus.cs, BookingsApi/BookingsApi.Contract/Requests/Enums/UpdateBookingStatus.cs, BookingsApi/BookingsApi.DAL/Queries/GetHearingShellByIdQuery.cs, BookingsApi/BookingsApi.IntegrationTests/Database/Queries/GetHearingShellByIdQueryHandlerDatabaseTests.cs, BookingsApi/BookingsApi.IntegrationTests/Features/Hearings.feature, BookingsApi/BookingsApi.IntegrationTests/Steps/HearingsSteps.cs, BookingsApi/BookingsApi.UnitTests/Controllers/HearingParticipantsController/AddParticipantsToHearingTests.cs, BookingsApi/BookingsApi.UnitTests/Controllers/HearingsController/BookNewHearingTests.cs, BookingsApi/BookingsApi.UnitTests/Controllers/HearingsController/CloneHearingTests.cs, BookingsApi/BookingsApi.UnitTests/Controllers/HearingsController/GetBookingStatusByIdTests.cs, BookingsApi/BookingsApi.UnitTests/DAL/Queries/GetHearingShellQueryTest.cs, BookingsApi/BookingsApi/Controllers/HearingParticipantsController.cs, BookingsApi/BookingsApi/Controllers/HearingsController.cs, BookingsApi/BookingsApi/nswag.json, BookingsApi/Testing.Common/Builders/Api/ApiUriFactory.cs
New query to retrieve hearing shell data. New endpoint to retrieve booking status. Removed update booking status to created when the judge is added instead this status will be updated from booking queue subscriber so the admin web can poll this status rather than for the conference
```
[ ] Yes
[ x] No
```
=> VIH-9607 Get booking status endpoint

BookingsApi/BookingsApi.Client/BookingsApiClient.cs, BookingsApi/BookingsApi.DAL/BookingsDbContext.cs, BookingsApi/BookingsApi.DAL/Commands/AddJusticeUserCommand.cs, BookingsApi/BookingsApi.DAL/Commands/DeleteJusticeUserCommand.cs, BookingsApi/BookingsApi.DAL/Commands/DeleteNonWorkingHoursCommand.cs, BookingsApi/BookingsApi.DAL/Exceptions/JusticeUserNotFoundException.cs, BookingsApi/BookingsApi.DAL/Migrations/20230223155544_AddDeletedColumnsForJusticeUser.Designer.cs, BookingsApi/BookingsApi.DAL/Migrations/20230223155544_AddDeletedColumnsForJusticeUser.cs, BookingsApi/BookingsApi.Domain/JusticeUser.cs, BookingsApi/BookingsApi.Domain/VhoNonAvailability.cs, BookingsApi/BookingsApi.Domain/VhoWorkHours.cs, BookingsApi/BookingsApi.IntegrationTests/Api/JusticeUsers/DeleteJusticeUserTests.cs, BookingsApi/BookingsApi.IntegrationTests/Database/Commands/AddJusticeUserCommandTests.cs, BookingsApi/BookingsApi.IntegrationTests/Database/Commands/DeleteJusticeUserCommandTests.cs, BookingsApi/BookingsApi.IntegrationTests/Database/Queries/GetAllocationHearingsBySearchQueryTests.cs, BookingsApi/BookingsApi.IntegrationTests/Database/Queries/GetJusticeUsersByUsernameQueryHandlerDatabaseTests.cs, BookingsApi/BookingsApi.IntegrationTests/Database/Queries/GetJusticeUsersListQueryHandlerDatabaseTests.cs, BookingsApi/BookingsApi.IntegrationTests/Database/Queries/GetVhoWorkHoursQueryHandlerDatabaseTests.cs, BookingsApi/BookingsApi.IntegrationTests/Helper/TestDataManager.cs, BookingsApi/BookingsApi.UnitTests/Controllers/JusticeUserControllerTests.cs, BookingsApi/BookingsApi.UnitTests/DAL/Services/HearingAllocationServiceTests.cs, BookingsApi/BookingsApi/Controllers/JusticeUserController.cs, BookingsApi/Testing.Common/Builders/Api/ApiUriFactory.cs
https://tools.hmcts.net/jira/browse/VIH-9367
- Adds an endpoint for (soft) deleting justice users
- Uses a global filter in the BookingsDbContext to automatically filter deleted justice users and work hours out of queries. This is overridden with IgnoreGlobalFilters() where necessary. More info on this approach here https://learn.microsoft.com/en-us/ef/core/querying/filters
```
[ ] Yes
[x] No
```
=> VIH-9367 Delete justice user

BookingsApi/BookingsApi.AcceptanceTests/Features/Persons.feature, BookingsApi/BookingsApi.AcceptanceTests/Models/AddParticipantRequest.cs, BookingsApi/BookingsApi.AcceptanceTests/Models/CreateHearingRequestBuilder.cs, BookingsApi/BookingsApi.AcceptanceTests/Models/SimpleBookNewHearingRequest.cs, BookingsApi/BookingsApi.AcceptanceTests/Steps/HearingsSteps.cs, BookingsApi/BookingsApi.AcceptanceTests/Steps/ParticipantsSteps.cs, BookingsApi/BookingsApi.AcceptanceTests/Steps/PersonsSteps.cs, BookingsApi/Testing.Common/Configuration/TestUsers.cs, BookingsApi/Testing.Common/Data/TestUser.cs, BookingsApi/Testing.Common/Data/TestUsers.cs
https://tools.hmcts.net/jira/browse/VIH-9675
Changes the acceptance tests to use an existing set of users rather than create new ones. These users have been added to an "Automation Tests" group in AAD so we know not to delete them.
Removes a test that is no longer valid now that we re-use users, there is already test coverage for that scenario in the integration tests.
```
[ ] Yes
[x] No
```
=> VIH-9675 Fix for automation tests creating lots of AAD accounts

BookingsApi/BookingsApi.Domain/Hearing.cs, BookingsApi/BookingsApi.UnitTests/DAL/Services/HearingAllocationServiceTests.cs
https://tools.hmcts.net/jira/browse/VIH-10032
Fixes an issue whereby a CSO cannot be automatically allocated to a hearing if they have already been allocated to another hearing after this date.
Use `Math.Abs` to ensure the time difference between hearings is always output as a positive value. This prevents `gapBetweenHearingsIsInsufficient` from always returning true when the scheduled date time of the hearing is before the scheduled date time of their allocated hearings.
```
[ ] Yes
[x] No
```
=> VIH-10032 45 hearings not automatically allocated for performance test

BookingsApi/BookingsApi.Domain/Hearing.cs, BookingsApi/BookingsApi.UnitTests/Domain/Hearing/AddParticipantTests.cs
VIH-10255
Booking a hearing with interpreters and a start time within 30 mins would cause a domain rule failure. The validation to check if an action was allowed did not take into account the hearing status.
=> VIH-10255 bug fix hearing change validation to only apply to confirmed hearings

BookingsApi/BookingsApi.UnitTests/Controllers/HearingsController/HearingsControllerTests.cs, BookingsApi/BookingsApi/Controllers/V1/HearingsController.cs, BookingsApi/BookingsApi/Mappings/V1/UpdateBookingStatusToBookingStatusMapper.cs, charts/vh-bookings-api/values.dev.template.yaml
https://tools.hmcts.net/jira/browse/VIH-10357
When the hearing is successfully created and the booking status is BookedWithoutJudge, it should be changed to ConfirmedWithoutJudge, not Created, so that the No Judge Assigned label appears in the UI.
There is a separate ticket in the backlog to refactor the endpoint so that the status transition is set by the domain rather than the api caller. The change in this PR is an intermediary solution until then.
=> VIH-10357 Fix incorrect booking status booking without a judge

BookingsApi/BookingsApi.Client/BookingsApiClient.cs, BookingsApi/BookingsApi.Contract/V1/Requests/ReassignJudiciaryJudgeRequest.cs, BookingsApi/BookingsApi.DAL/Commands/ReassignJudiciaryJudgeCommand.cs, BookingsApi/BookingsApi.DAL/Commands/UpdateHearingParticipantsCommand.cs, BookingsApi/BookingsApi.DAL/Dtos/NewJudiciaryJudge.cs, BookingsApi/BookingsApi.DAL/Services/HearingService.cs, BookingsApi/BookingsApi.Domain/Hearing.cs, BookingsApi/BookingsApi.Domain/JudiciaryParticipants/JudiciaryJudge.cs, BookingsApi/BookingsApi.Domain/Validations/DomainRuleErrorMessages.cs, BookingsApi/BookingsApi.IntegrationTests/Api/V1/JudiciaryParticipants/ReassignJudiciaryJudgeTests.cs, BookingsApi/BookingsApi.IntegrationTests/Database/Commands/ReassignJudiciaryJudgeCommandTests.cs, BookingsApi/BookingsApi.IntegrationTests/Database/Commands/UpdateHearingParticipantsCommandHandlerTests.cs, BookingsApi/BookingsApi.UnitTests/Domain/Hearing/ReassignJudgeTests.cs, BookingsApi/BookingsApi.UnitTests/Domain/Hearing/ReassignJudiciaryJudgeTests.cs, BookingsApi/BookingsApi.UnitTests/Validation/V1/ReassignJudiciaryJudgeRequestValidationTests.cs, BookingsApi/BookingsApi/Controllers/V1/JudiciaryParticipantsController.cs, BookingsApi/BookingsApi/Validations/V1/ReassignJudiciaryJudgeRequestValidation.cs, BookingsApi/Testing.Common/Builders/Api/ApiUriFactory.cs, BookingsApi/Testing.Common/Builders/Domain/JudgeBuilder.cs
https://tools.hmcts.net/jira/browse/VIH-10361
Due to new domain rules added to bookings api, the judge can no longer be changed by removing the participant and adding the new one.
As a solution to this, a new operation for reassigning the judge has been added (ReassignJudge for V1, ReassignJudiciaryJudge for V2). This is called to update the judge instead of removing and adding the participants.
In V1 the participant updates are coordinated from bookings API, but in V2 they are part of admin web, so a new API endpoint has been added for reassigning the judge which admin web can call as part of V2.
=> VIH-10361 Fix for unable to update judge last minute

BookingsApi/BookingsApi.Domain/Hearing.cs, BookingsApi/BookingsApi.IntegrationTests/Api/V1/JudiciaryParticipants/ReassignJudiciaryJudgeTests.cs, BookingsApi/BookingsApi.UnitTests/Domain/Hearing/ReassignJudiciaryJudgeTests.cs
https://tools.hmcts.net/jira/browse/VIH-10380
Fixes an issue where if you book a V2 hearing without a judge, then edit and add a judge, the booking status remains ConfirmedWithoutJudge, instead of changing to Created
=> VIH-10380 Booking status not updating after adding judge with V2 on

BookingsApi/BookingsApi.DAL/Commands/UpdateHearingParticipantsCommand.cs, BookingsApi/BookingsApi.IntegrationTests/Api/V1/HearingParticipants/UpdateHearingParticipantsTests.cs, BookingsApi/BookingsApi.IntegrationTests/ApiTest.cs, BookingsApi/BookingsApi.IntegrationTests/Helper/TestDataManager.cs, BookingsApi/BookingsApi/Services/HearingParticipantService.cs
https://tools.hmcts.net/jira/browse/VIH-10361
Changed NewParticipants added to the command handler, to be created as a new list of values rather than by reference, so that when the handler removes the judge from the list, it doesnt effect the NewParticipants list which needs to be passed to the integration events to update the conference
=> VIH-10414 Updated UpdateHearingParticipantsCommand NewParticipant list to be a list of values rather than reference

BookingsApi/BookingsApi.Infrastructure.Services/AsynchronousProcesses/MultidayHearingAsynchronousProcess.cs, BookingsApi/BookingsApi.Infrastructure.Services/Dtos/HearingConfirmationForParticipantDto.cs, BookingsApi/BookingsApi.Infrastructure.Services/EventDtoMappers.cs, BookingsApi/BookingsApi.Infrastructure.Services/HearingConfirmationForParticipantDtoMapper.cs, BookingsApi/BookingsApi.Infrastructure.Services/IntegrationEvents/Events/MultiDayHearingIntegrationEvent.cs, BookingsApi/BookingsApi.Infrastructure.Services/Publishers/MultidayHearingNotificationEventPublisher.cs, BookingsApi/BookingsApi.IntegrationTests/Api/V1/Hearings/CloneHearingTests.cs, BookingsApi/BookingsApi.UnitTests/EventPublisherFactoryInstance.cs, BookingsApi/BookingsApi.UnitTests/Infrastructure.Services/EventDtoMappersTests.cs, BookingsApi/BookingsApi.UnitTests/Services/ClonedMultidaysAsynchronousProcessTests.cs
https://tools.hmcts.net/jira/browse/VIH-10493
- Pass `TotalDays` property to the published event
- Publish events for judiciary participants
- Fix typo in publisher name
- Fix typo in dto property name (this was actually causing the ParticipantId to deserialise into an empty guid in BQS)
=> VIH-10493 Fix - multiday notifications not sent when new notify templates are toggled off

BookingsApi/BookingsApi.Contract/Interfaces/Requests/IUpdateParticipantRequest.cs, BookingsApi/BookingsApi.IntegrationTests/Api/V1/HearingParticipants/UpdateHearingParticipantsTests.cs, BookingsApi/BookingsApi.IntegrationTests/Api/V1/Hearings/UpdateHearingsInGroupTests.cs, BookingsApi/BookingsApi.IntegrationTests/Api/V2/HearingParticipants/UpdateHearingParticipantsV2Tests.cs, BookingsApi/BookingsApi.IntegrationTests/Api/V2/Hearings/UpdateHearingsInGroupV2Tests.cs, BookingsApi/BookingsApi/Controllers/V1/HearingParticipantsController.cs, BookingsApi/BookingsApi/Services/HearingParticipantService.cs
https://tools.hmcts.net/jira/browse/VIH-10475
Have added function to UpdateParticipants methods, that determines whether an existing participant is actually being updated. If not will exclude from list sent to BQS/video-api. This is because it will overwrite any video participant data, that may have been changed via video-web i.e. DisplayName
=> VIH-10475 Filter existing participants before publish

BookingsApi/BookingsApi.DAL/Services/HearingService.cs, BookingsApi/BookingsApi.Domain/Hearing.cs, BookingsApi/BookingsApi.Domain/Validations/DomainRuleErrorMessages.cs, BookingsApi/BookingsApi.IntegrationTests/Api/V1/Hearings/CloneHearingTests.cs, BookingsApi/BookingsApi.UnitTests/Controllers/HearingsController/CloneHearingTests.cs, BookingsApi/BookingsApi.UnitTests/Domain/Hearing/RenameHearingForMultiDayBooking.cs, BookingsApi/BookingsApi/Controllers/V1/HearingsController.cs
https://tools.hmcts.net/jira/browse/VIH-10521
- The Hearing domain method `UpdateCase` does not allow updates to a hearing that is due to start within 30 minutes. This rule needs to be bypassed as part of the multi-day hearing clone process (which renames them to Day 1 of 2, etc) so introduce a new a method - `RenameHearingForMultiDayBooking`
- Update tests to create the initial hearing with a status of Created
- Add a test for the 30 minute scenario
=> VIH-10521 Fix error creating multi-day booking scheduled 30 minutes from now

BookingsApi/BookingsApi.Domain/Hearing.cs, BookingsApi/BookingsApi.IntegrationTests/Api/V2/Hearings/UpdateHearingsInGroupV2Tests.cs, BookingsApi/BookingsApi.UnitTests/Domain/Hearing/UpdateJudiciaryParticipantTests.cs, BookingsApi/BookingsApi/Services/UpdateHearingService.cs
https://tools.hmcts.net/jira/browse/VIH-10637
Fixes an error updating hearings in group last minute (30 minutes before a hearing starts)
The culprit is a domain rule which prevents updates to judiciary participants 30 minutes before the hearing starts. This rule is triggering even if there are not actually any edits being made to the judiciary participants.
To avoid this, don't attempt to update the judiciary participants if they have not actually changed.
- Update tests with additional coverage
- Add handling for participants in request not existing on hearing
=> VIH-10637 Fix error updating hearings in group last minute

BookingsApi/BookingsApi.IntegrationTests/Api/V2/Hearings/UpdateHearingsInGroupV2Tests.cs, BookingsApi/BookingsApi/Validations/V2/UpdateHearingsInGroupRequestRefDataValidationV2.cs
https://tools.hmcts.net/jira/browse/VIH-10685
Extension of a previous ticket [(VIH-10537)](https://tools.hmcts.net/jira/browse/VIH-10537) - applies this validation rule to the multi-hearing edit
We validate in an earlier step to check whether any of the dates are the same for the hearings in the request. This adds an additional check against the existing hearings that are not in the request
=> VIH-10685 Prevent changing hearing dates to be same in multi day hearing

BookingsApi/BookingsApi.DAL/Helper/CloneHearingToCommandMapper.cs, BookingsApi/BookingsApi.DAL/Helper/NewEndpointGenerator.cs, BookingsApi/BookingsApi.UnitTests/Controllers/HearingsController/BookNewHearingTests.cs, BookingsApi/BookingsApi/Mappings/V1/BookNewHearingRequestToCreateVideoHearingCommandMapper.cs, BookingsApi/BookingsApi/Mappings/V2/BookNewHearingRequestV2ToCreateVideoHearingCommandMapper.cs
VIH-10759 
Introduce a NewEndpointGenerator.cs to capture SIPs with the same value during the same creation operation. As frameworks and hardware performance improves the ticks do not guarantee a reliable unique list of values when a request contains multiple endpoints.
=> VIH-10759 bug fix adding multiple endpoints in a single request

BookingsApi/BookingsApi.UnitTests/Mappings/V2/HearingToDetailsResponseV2MapperTests.cs, BookingsApi/BookingsApi/Mappings/V2/CaseToResponseV2Mapper.cs, BookingsApi/BookingsApi/Mappings/V2/Extensions/ContractExtensions.cs, BookingsApi/BookingsApi/Mappings/V2/HearingToDetailsResponseV2Mapper.cs
https://tools.hmcts.net/jira/browse/VIH-11047
Changes the HearingDetailsResponse to populate the "Allocated to" properties with the calculated values from the VideoHearingHelper. This makes their values consistent with the other responses and removes the need to re-calculate them on the client
=> VIH-11047 Change hearing details response to return allocated to not required where applicable

BookingsApi/BookingsApi.DAL/Mappings/JudiciaryParticipantMap.cs, BookingsApi/BookingsApi.DAL/Mappings/VhoNonAvailabilityMap.cs, BookingsApi/BookingsApi.DAL/Mappings/VhoWorkHoursMap.cs, BookingsApi/BookingsApi.DAL/Migrations/20250114153413_ChangeTrackingColumnsToNonNullable.Designer.cs, BookingsApi/BookingsApi.DAL/Migrations/20250114153413_ChangeTrackingColumnsToNonNullable.cs, BookingsApi/BookingsApi.Domain/Allocation.cs, BookingsApi/BookingsApi.Domain/Ddd/AggregateRoot.cs, BookingsApi/BookingsApi.Domain/Ddd/TrackableAggregateRoot.cs, BookingsApi/BookingsApi.Domain/Hearing.cs, BookingsApi/BookingsApi.Domain/ITrackable.cs, BookingsApi/BookingsApi.Domain/JudiciaryParticipant.cs, BookingsApi/BookingsApi.Domain/JudiciaryPerson.cs, BookingsApi/BookingsApi.Domain/JudiciaryPersonStaging.cs, BookingsApi/BookingsApi.Domain/ParticipantBase.cs, BookingsApi/BookingsApi.Domain/Participants/Participant.cs, BookingsApi/BookingsApi.Domain/Person.cs, BookingsApi/BookingsApi.Domain/VhoWorkHours.cs, BookingsApi/BookingsApi.Infrastructure.Services/Publishers/PublisherHelper.cs, BookingsApi/BookingsApi.IntegrationTests/Database/Commands/UpdateEndPointOfHearingCommandTests.cs
https://tools.hmcts.net/jira/browse/VIH-10139
- Remove CreatedDate and UpdatedDate from entities - inherit through TrackableEntity instead
- Change CreatedDate and UpdatedDate from nullable to non-nullable in TrackableEntity
- Setting the Id within the JudiciaryParticipant's constructor is no longer needed - this is now done through the ParticipantBase class
=> VIH-10139 Standardise trackable entities

BookingsApi/BookingsApi.DAL/Commands/RemoveEndPointFromHearingCommand.cs, BookingsApi/BookingsApi.Domain/Hearing.cs, BookingsApi/BookingsApi.IntegrationTests/Api/V1/Endpoints/RemoveEndPointFromHearingTests.cs
https://tools.hmcts.net/jira/browse/VIH-11275
missing includes from remove endpoint command, means screening entity composite table was not being cleared down when endpoint is removed, causing fk contraint on context update
=> VIH-11275 Error removing JVS endpoint from hearing with screening
